// This file was generated by gir (https://github.com/gtk-rs/gir)
// from upower-gir-files
// DO NOT EDIT

use crate::{Device, ffi};
use glib::{
    object::ObjectType as _,
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::{boxed::Box as Box_, pin::Pin};

#[cfg(feature = "gio_v2_22")]
#[cfg_attr(docsrs, doc(cfg(feature = "gio_v2_22")))]
glib::wrapper! {
    ///
    ///
    /// ## Properties
    ///
    ///
    /// #### `daemon-version`
    ///  The daemon version.
    ///
    /// Readable
    ///
    ///
    /// #### `lid-is-closed`
    ///  If the laptop lid is closed.
    ///
    /// Readable
    ///
    ///
    /// #### `lid-is-present`
    ///  If a laptop lid is present.
    ///
    /// Readable
    ///
    ///
    /// #### `on-battery`
    ///  If the computer is on battery power.
    ///
    /// Readable
    ///
    /// ## Signals
    ///
    ///
    /// #### `device-added`
    ///  The ::device-added signal is emitted when a power device is added.
    ///
    ///
    ///
    ///
    /// #### `device-removed`
    ///  The ::device-removed signal is emitted when a power device is removed.
    ///
    ///
    ///
    /// # Implements
    ///
    /// [`ClientExt`][trait@crate::prelude::ClientExt], [`trait@gio::prelude::AsyncInitableExt`], [`trait@gio::prelude::InitableExt`]
    #[doc(alias = "UpClient")]
    pub struct Client(Object<ffi::UpClient, ffi::UpClientClass>) @implements gio::AsyncInitable, gio::Initable;

    match fn {
        type_ => || ffi::up_client_get_type(),
    }
}

#[cfg(not(any(feature = "gio_v2_22")))]
#[cfg(feature = "gio_v2_22")]
glib::wrapper! {
    #[doc(alias = "UpClient")]
    pub struct Client(Object<ffi::UpClient, ffi::UpClientClass>) @implements gio::Initable;

    match fn {
        type_ => || ffi::up_client_get_type(),
    }
}

#[cfg(not(any(feature = "gio_v2_22")))]
glib::wrapper! {
    #[doc(alias = "UpClient")]
    pub struct Client(Object<ffi::UpClient, ffi::UpClientClass>);

    match fn {
        type_ => || ffi::up_client_get_type(),
    }
}

impl Client {
    pub const NONE: Option<&'static Client> = None;

    /// Creates a new [`Client`][crate::Client] object. If connecting to upowerd on D-Bus fails,
    /// this returns [`None`] and prints out a warning with the error message.
    /// Consider using [`new_full()`][Self::new_full()] instead which allows you to handle errors
    /// and canceling long operations yourself.
    ///
    /// # Returns
    ///
    /// a new UpClient object, or [`None`] on failure.
    #[doc(alias = "up_client_new")]
    pub fn new() -> Client {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::up_client_new()) }
    }

    /// Creates a new [`Client`][crate::Client] object. If connecting to upowerd on D-Bus fails,
    /// this returns [`None`] and sets `error`.
    /// ## `cancellable`
    /// A [`gio::Cancellable`][crate::gio::Cancellable] or [`None`].
    ///
    /// # Returns
    ///
    /// a new UpClient object, or [`None`] on failure.
    #[doc(alias = "up_client_new_full")]
    pub fn new_full(
        cancellable: Option<&impl IsA<gio::Cancellable>>,
    ) -> Result<Client, glib::Error> {
        assert_initialized_main_thread!();
        unsafe {
            let mut error = std::ptr::null_mut();
            let ret = ffi::up_client_new_full(
                cancellable.map(|p| p.as_ref()).to_glib_none().0,
                &mut error,
            );
            if error.is_null() {
                Ok(from_glib_full(ret))
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    /// Asynchronously creates a new [`Client`][crate::Client] object.
    ///
    /// This is an asynchronous failable function.
    /// ## `cancellable`
    /// a [`gio::Cancellable`][crate::gio::Cancellable] or [`None`]
    /// ## `callback`
    /// a `GAsyncReadyCallback` to call when the request is satisfied
    #[doc(alias = "up_client_new_async")]
    pub fn new_async<P: FnOnce(Result<Client, glib::Error>) + 'static>(
        cancellable: Option<&impl IsA<gio::Cancellable>>,
        callback: P,
    ) {
        assert_initialized_main_thread!();

        let main_context = glib::MainContext::ref_thread_default();
        let is_main_context_owner = main_context.is_owner();
        let has_acquired_main_context = (!is_main_context_owner)
            .then(|| main_context.acquire().ok())
            .flatten();
        assert!(
            is_main_context_owner || has_acquired_main_context.is_some(),
            "Async operations only allowed if the thread is owning the MainContext"
        );

        let user_data: Box_<glib::thread_guard::ThreadGuard<P>> =
            Box_::new(glib::thread_guard::ThreadGuard::new(callback));
        unsafe extern "C" fn new_async_trampoline<
            P: FnOnce(Result<Client, glib::Error>) + 'static,
        >(
            _source_object: *mut glib::gobject_ffi::GObject,
            res: *mut gio::ffi::GAsyncResult,
            user_data: glib::ffi::gpointer,
        ) {
            unsafe {
                let mut error = std::ptr::null_mut();
                let ret = ffi::up_client_new_finish(res, &mut error);
                let result = if error.is_null() {
                    Ok(from_glib_full(ret))
                } else {
                    Err(from_glib_full(error))
                };
                let callback: Box_<glib::thread_guard::ThreadGuard<P>> =
                    Box_::from_raw(user_data as *mut _);
                let callback: P = callback.into_inner();
                callback(result);
            }
        }
        let callback = new_async_trampoline::<P>;
        unsafe {
            ffi::up_client_new_async(
                cancellable.map(|p| p.as_ref()).to_glib_none().0,
                Some(callback),
                Box_::into_raw(user_data) as *mut _,
            );
        }
    }

    pub fn new_future()
    -> Pin<Box_<dyn std::future::Future<Output = Result<Client, glib::Error>> + 'static>> {
        skip_assert_initialized!();
        Box_::pin(gio::GioFuture::new(&(), move |_obj, cancellable, send| {
            Self::new_async(Some(cancellable), move |res| {
                send.resolve(res);
            });
        }))
    }
}

impl Default for Client {
    fn default() -> Self {
        Self::new()
    }
}

/// Trait containing all [`struct@Client`] methods.
///
/// # Implementors
///
/// [`Client`][struct@crate::Client]
pub trait ClientExt: IsA<Client> + 'static {
    /// Gets a string representing the configured critical action,
    /// depending on availability.
    ///
    /// # Returns
    ///
    /// the action name, or [`None`] on error.
    #[doc(alias = "up_client_get_critical_action")]
    #[doc(alias = "get_critical_action")]
    fn critical_action(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_full(ffi::up_client_get_critical_action(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get UPower daemon version.
    ///
    /// # Returns
    ///
    /// string containing the daemon version, e.g. 008
    #[doc(alias = "up_client_get_daemon_version")]
    #[doc(alias = "get_daemon_version")]
    #[doc(alias = "daemon-version")]
    fn daemon_version(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::up_client_get_daemon_version(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get a copy of the device objects.
    ///
    /// # Returns
    ///
    /// an array of [`Device`][crate::Device] objects or [`None`] on error, free with `g_ptr_array_unref()`
    #[doc(alias = "up_client_get_devices2")]
    #[doc(alias = "get_devices2")]
    fn devices2(&self) -> Vec<Device> {
        unsafe {
            FromGlibPtrContainer::from_glib_full(ffi::up_client_get_devices2(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Asynchronously fetches the list of [`Device`][crate::Device] objects.
    /// ## `cancellable`
    /// a [`gio::Cancellable`][crate::gio::Cancellable] or [`None`]
    /// ## `callback`
    /// a `GAsyncReadyCallback` to call when the request is satisfied
    #[doc(alias = "up_client_get_devices_async")]
    #[doc(alias = "get_devices_async")]
    fn devices_async<P: FnOnce(Result<Vec<Device>, glib::Error>) + 'static>(
        &self,
        cancellable: Option<&impl IsA<gio::Cancellable>>,
        callback: P,
    ) {
        let main_context = glib::MainContext::ref_thread_default();
        let is_main_context_owner = main_context.is_owner();
        let has_acquired_main_context = (!is_main_context_owner)
            .then(|| main_context.acquire().ok())
            .flatten();
        assert!(
            is_main_context_owner || has_acquired_main_context.is_some(),
            "Async operations only allowed if the thread is owning the MainContext"
        );

        let user_data: Box_<glib::thread_guard::ThreadGuard<P>> =
            Box_::new(glib::thread_guard::ThreadGuard::new(callback));
        unsafe extern "C" fn devices_async_trampoline<
            P: FnOnce(Result<Vec<Device>, glib::Error>) + 'static,
        >(
            _source_object: *mut glib::gobject_ffi::GObject,
            res: *mut gio::ffi::GAsyncResult,
            user_data: glib::ffi::gpointer,
        ) {
            unsafe {
                let mut error = std::ptr::null_mut();
                let ret =
                    ffi::up_client_get_devices_finish(_source_object as *mut _, res, &mut error);
                let result = if error.is_null() {
                    Ok(FromGlibPtrContainer::from_glib_full(ret))
                } else {
                    Err(from_glib_full(error))
                };
                let callback: Box_<glib::thread_guard::ThreadGuard<P>> =
                    Box_::from_raw(user_data as *mut _);
                let callback: P = callback.into_inner();
                callback(result);
            }
        }
        let callback = devices_async_trampoline::<P>;
        unsafe {
            ffi::up_client_get_devices_async(
                self.as_ref().to_glib_none().0,
                cancellable.map(|p| p.as_ref()).to_glib_none().0,
                Some(callback),
                Box_::into_raw(user_data) as *mut _,
            );
        }
    }

    fn devices_future(
        &self,
    ) -> Pin<Box_<dyn std::future::Future<Output = Result<Vec<Device>, glib::Error>> + 'static>>
    {
        Box_::pin(gio::GioFuture::new(self, move |obj, cancellable, send| {
            obj.devices_async(Some(cancellable), move |res| {
                send.resolve(res);
            });
        }))
    }

    /// Get the composite display device.
    ///
    /// # Returns
    ///
    /// a [`Device`][crate::Device] object, or [`None`] on error.
    #[doc(alias = "up_client_get_display_device")]
    #[doc(alias = "get_display_device")]
    fn display_device(&self) -> Option<Device> {
        unsafe {
            from_glib_full(ffi::up_client_get_display_device(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get whether the laptop lid is closed.
    ///
    /// # Returns
    ///
    /// [`true`] if lid is closed or [`false`] otherwise.
    #[doc(alias = "up_client_get_lid_is_closed")]
    #[doc(alias = "get_lid_is_closed")]
    #[doc(alias = "lid-is-closed")]
    fn is_lid_is_closed(&self) -> bool {
        unsafe {
            from_glib(ffi::up_client_get_lid_is_closed(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get whether a laptop lid is present on this machine.
    ///
    /// # Returns
    ///
    /// [`true`] if the machine has a laptop lid
    #[doc(alias = "up_client_get_lid_is_present")]
    #[doc(alias = "get_lid_is_present")]
    #[doc(alias = "lid-is-present")]
    fn is_lid_is_present(&self) -> bool {
        unsafe {
            from_glib(ffi::up_client_get_lid_is_present(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Get whether the system is running on battery power.
    ///
    /// # Returns
    ///
    /// [`true`] if the system is currently running on battery, [`false`] otherwise.
    #[doc(alias = "up_client_get_on_battery")]
    #[doc(alias = "get_on_battery")]
    #[doc(alias = "on-battery")]
    fn is_on_battery(&self) -> bool {
        unsafe {
            from_glib(ffi::up_client_get_on_battery(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// The ::device-added signal is emitted when a power device is added.
    /// ## `device`
    /// the [`Device`][crate::Device] that was added.
    #[doc(alias = "device-added")]
    fn connect_device_added<F: Fn(&Self, &Device) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn device_added_trampoline<
            P: IsA<Client>,
            F: Fn(&P, &Device) + 'static,
        >(
            this: *mut ffi::UpClient,
            device: *mut ffi::UpDevice,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(
                    Client::from_glib_borrow(this).unsafe_cast_ref(),
                    &from_glib_borrow(device),
                )
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"device-added".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    device_added_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    /// The ::device-removed signal is emitted when a power device is removed.
    /// ## `object_path`
    /// the object path of the [`Device`][crate::Device] that was removed.
    #[doc(alias = "device-removed")]
    fn connect_device_removed<F: Fn(&Self, &str) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn device_removed_trampoline<
            P: IsA<Client>,
            F: Fn(&P, &str) + 'static,
        >(
            this: *mut ffi::UpClient,
            object_path: *mut std::ffi::c_char,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(
                    Client::from_glib_borrow(this).unsafe_cast_ref(),
                    &glib::GString::from_glib_borrow(object_path),
                )
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"device-removed".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    device_removed_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "daemon-version")]
    fn connect_daemon_version_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_daemon_version_trampoline<
            P: IsA<Client>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpClient,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Client::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::daemon-version".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_daemon_version_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "lid-is-closed")]
    fn connect_lid_is_closed_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_lid_is_closed_trampoline<
            P: IsA<Client>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpClient,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Client::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::lid-is-closed".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_lid_is_closed_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "lid-is-present")]
    fn connect_lid_is_present_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_lid_is_present_trampoline<
            P: IsA<Client>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpClient,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Client::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::lid-is-present".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_lid_is_present_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "on-battery")]
    fn connect_on_battery_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_on_battery_trampoline<P: IsA<Client>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpClient,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Client::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::on-battery".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_on_battery_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<Client>> ClientExt for O {}
