// This file was generated by gir (https://github.com/gtk-rs/gir)
// from upower-gir-files
// DO NOT EDIT

use crate::{DeviceKind, DeviceLevel, DeviceState, DeviceTechnology, HistoryItem, StatsItem, ffi};
use glib::{
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    ///
    ///
    /// ## Properties
    ///
    ///
    /// #### `battery-level`
    ///  The battery level, e.g. [`DeviceLevel::Critical`][crate::DeviceLevel::Critical]. If this is something
    /// other than [`DeviceLevel::None`][crate::DeviceLevel::None], then User Interfaces should use this
    /// approximate level instead of percentages.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `capacity`
    ///  The percentage capacity of the device where 100% means the device has
    /// the same charge potential as when it was manufactured.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `capacity-level`
    ///  Coarse representation of battery capacity. The value is one of the following:
    /// Unknown, Critical, Low, Normal, High, and Full.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `charge-cycles`
    ///  The number of charge cycles for the battery, or -1 if unknown
    /// or non-applicable.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `charge-end-threshold`
    ///  The charge end threshold of a battery.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `charge-start-threshold`
    ///  The charge start threshold of a battery.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `charge-threshold-enabled`
    ///  The charge threshold of a battery is enabled, or false if unknown
    /// or non-applicable.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `charge-threshold-supported`
    ///  The charge threshold of a battery is supported, or false if unknown
    /// or non-applicable.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `energy`
    ///  The energy left in the device. Measured in mWh.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `energy-empty`
    ///  The energy the device will have when it is empty. This is usually zero.
    /// Measured in mWh.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `energy-full`
    ///  The amount of energy when the device is fully charged. Measured in mWh.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `energy-full-design`
    ///  The amount of energy when the device was brand new. Measured in mWh.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `energy-rate`
    ///  The rate of discharge or charge. Measured in mW.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `has-history`
    ///  If the device has history data that might be useful.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `has-statistics`
    ///  If the device has statistics data that might be useful.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `icon-name`
    ///  The icon name, following the Icon Naming Specification
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `is-present`
    ///  If the device is present, as some devices like laptop batteries
    /// can be removed, leaving an empty bay that is still technically a
    /// device.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `is-rechargeable`
    ///  If the device has a rechargeable battery.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `kind`
    ///  The device kind, e.g. [`DeviceKind::Keyboard`][crate::DeviceKind::Keyboard].
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `luminosity`
    ///  The current luminosity of the device.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `model`
    ///  The model of the device.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `native-path`
    ///  The native path of the device, useful for direct device access.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `online`
    ///  If the device is online, i.e. connected.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `percentage`
    ///  The percentage charge of the device. Note that if the battery level property
    /// is something other than [`DeviceLevel::None`][crate::DeviceLevel::None], then this percentage is an
    /// approximation, and should not be used a number to display to the user.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `power-supply`
    ///  If the device is powering the system.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `serial`
    ///  The serial number of the device.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `state`
    ///  The state the device is in at this time, e.g. [`DeviceState::Empty`][crate::DeviceState::Empty].
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `technology`
    ///  The battery technology e.g. [`DeviceTechnology::LithiumIon`][crate::DeviceTechnology::LithiumIon].
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `temperature`
    ///  The temperature of the device in degrees Celsius.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `time-to-empty`
    ///  The amount of time until the device is empty.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `time-to-full`
    ///  The amount of time until the device is fully charged.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `update-time`
    ///  The last time the device was updated.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `vendor`
    ///  The vendor of the device.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `voltage`
    ///  The current voltage of the device.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `voltage-max-design`
    ///  Readable | Writeable
    ///
    ///
    /// #### `voltage-min-design`
    ///  Readable | Writeable
    ///
    ///
    /// #### `warning-level`
    ///  The warning level e.g. [`DeviceLevel::Critical`][crate::DeviceLevel::Critical].
    ///
    /// Readable | Writeable
    ///
    /// # Implements
    ///
    /// [`DeviceExt`][trait@crate::prelude::DeviceExt]
    #[doc(alias = "UpDevice")]
    pub struct Device(Object<ffi::UpDevice, ffi::UpDeviceClass>);

    match fn {
        type_ => || ffi::up_device_get_type(),
    }
}

impl Device {
    pub const NONE: Option<&'static Device> = None;

    /// Creates a new [`Device`][crate::Device] object.
    ///
    /// # Returns
    ///
    /// a new UpDevice object.
    #[doc(alias = "up_device_new")]
    pub fn new() -> Device {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::up_device_new()) }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`Device`] objects.
    ///
    /// This method returns an instance of [`DeviceBuilder`](crate::builders::DeviceBuilder) which can be used to create [`Device`] objects.
    pub fn builder() -> DeviceBuilder {
        DeviceBuilder::new()
    }

    /// Converts a string to a [`DeviceKind`][crate::DeviceKind].
    ///
    /// # Returns
    ///
    /// enumerated value
    #[doc(alias = "up_device_kind_from_string")]
    pub fn kind_from_string(type_: &str) -> DeviceKind {
        assert_initialized_main_thread!();
        unsafe { from_glib(ffi::up_device_kind_from_string(type_.to_glib_none().0)) }
    }

    /// Converts a [`DeviceKind`][crate::DeviceKind] to a string.
    ///
    /// # Returns
    ///
    /// identifier string
    #[doc(alias = "up_device_kind_to_string")]
    pub fn kind_to_string(type_enum: DeviceKind) -> Option<glib::GString> {
        assert_initialized_main_thread!();
        unsafe { from_glib_none(ffi::up_device_kind_to_string(type_enum.into_glib())) }
    }

    /// Converts a string to a [`DeviceLevel`][crate::DeviceLevel].
    ///
    /// # Returns
    ///
    /// enumerated value
    #[doc(alias = "up_device_level_from_string")]
    pub fn level_from_string(level: &str) -> DeviceLevel {
        assert_initialized_main_thread!();
        unsafe { from_glib(ffi::up_device_level_from_string(level.to_glib_none().0)) }
    }

    /// Converts a [`DeviceLevel`][crate::DeviceLevel] to a string.
    ///
    /// # Returns
    ///
    /// identifier string
    #[doc(alias = "up_device_level_to_string")]
    pub fn level_to_string(level_enum: DeviceLevel) -> Option<glib::GString> {
        assert_initialized_main_thread!();
        unsafe { from_glib_none(ffi::up_device_level_to_string(level_enum.into_glib())) }
    }

    /// Converts a string to a [`DeviceState`][crate::DeviceState].
    ///
    /// # Returns
    ///
    /// enumerated value
    #[doc(alias = "up_device_state_from_string")]
    pub fn state_from_string(state: &str) -> DeviceState {
        assert_initialized_main_thread!();
        unsafe { from_glib(ffi::up_device_state_from_string(state.to_glib_none().0)) }
    }

    /// Converts a [`DeviceState`][crate::DeviceState] to a string.
    ///
    /// # Returns
    ///
    /// identifier string
    #[doc(alias = "up_device_state_to_string")]
    pub fn state_to_string(state_enum: DeviceState) -> Option<glib::GString> {
        assert_initialized_main_thread!();
        unsafe { from_glib_none(ffi::up_device_state_to_string(state_enum.into_glib())) }
    }

    /// Converts a string to a [`DeviceTechnology`][crate::DeviceTechnology].
    ///
    /// # Returns
    ///
    /// enumerated value
    #[doc(alias = "up_device_technology_from_string")]
    pub fn technology_from_string(technology: &str) -> DeviceTechnology {
        assert_initialized_main_thread!();
        unsafe {
            from_glib(ffi::up_device_technology_from_string(
                technology.to_glib_none().0,
            ))
        }
    }

    /// Converts a [`DeviceTechnology`][crate::DeviceTechnology] to a string.
    ///
    /// # Returns
    ///
    /// identifier string
    #[doc(alias = "up_device_technology_to_string")]
    pub fn technology_to_string(technology_enum: DeviceTechnology) -> Option<glib::GString> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::up_device_technology_to_string(
                technology_enum.into_glib(),
            ))
        }
    }
}

impl Default for Device {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`Device`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeviceBuilder {
    builder: glib::object::ObjectBuilder<'static, Device>,
}

impl DeviceBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    /// The battery level, e.g. [`DeviceLevel::Critical`][crate::DeviceLevel::Critical]. If this is something
    /// other than [`DeviceLevel::None`][crate::DeviceLevel::None], then User Interfaces should use this
    /// approximate level instead of percentages.
    pub fn battery_level(self, battery_level: u32) -> Self {
        Self {
            builder: self.builder.property("battery-level", battery_level),
        }
    }

    /// The percentage capacity of the device where 100% means the device has
    /// the same charge potential as when it was manufactured.
    pub fn capacity(self, capacity: f64) -> Self {
        Self {
            builder: self.builder.property("capacity", capacity),
        }
    }

    /// Coarse representation of battery capacity. The value is one of the following:
    /// Unknown, Critical, Low, Normal, High, and Full.
    pub fn capacity_level(self, capacity_level: impl Into<glib::GString>) -> Self {
        Self {
            builder: self
                .builder
                .property("capacity-level", capacity_level.into()),
        }
    }

    /// The number of charge cycles for the battery, or -1 if unknown
    /// or non-applicable.
    pub fn charge_cycles(self, charge_cycles: i32) -> Self {
        Self {
            builder: self.builder.property("charge-cycles", charge_cycles),
        }
    }

    /// The charge end threshold of a battery.
    pub fn charge_end_threshold(self, charge_end_threshold: u32) -> Self {
        Self {
            builder: self
                .builder
                .property("charge-end-threshold", charge_end_threshold),
        }
    }

    /// The charge start threshold of a battery.
    pub fn charge_start_threshold(self, charge_start_threshold: u32) -> Self {
        Self {
            builder: self
                .builder
                .property("charge-start-threshold", charge_start_threshold),
        }
    }

    /// The charge threshold of a battery is enabled, or false if unknown
    /// or non-applicable.
    pub fn charge_threshold_enabled(self, charge_threshold_enabled: bool) -> Self {
        Self {
            builder: self
                .builder
                .property("charge-threshold-enabled", charge_threshold_enabled),
        }
    }

    /// The charge threshold of a battery is supported, or false if unknown
    /// or non-applicable.
    pub fn charge_threshold_supported(self, charge_threshold_supported: bool) -> Self {
        Self {
            builder: self
                .builder
                .property("charge-threshold-supported", charge_threshold_supported),
        }
    }

    /// The energy left in the device. Measured in mWh.
    pub fn energy(self, energy: f64) -> Self {
        Self {
            builder: self.builder.property("energy", energy),
        }
    }

    /// The energy the device will have when it is empty. This is usually zero.
    /// Measured in mWh.
    pub fn energy_empty(self, energy_empty: f64) -> Self {
        Self {
            builder: self.builder.property("energy-empty", energy_empty),
        }
    }

    /// The amount of energy when the device is fully charged. Measured in mWh.
    pub fn energy_full(self, energy_full: f64) -> Self {
        Self {
            builder: self.builder.property("energy-full", energy_full),
        }
    }

    /// The amount of energy when the device was brand new. Measured in mWh.
    pub fn energy_full_design(self, energy_full_design: f64) -> Self {
        Self {
            builder: self
                .builder
                .property("energy-full-design", energy_full_design),
        }
    }

    /// The rate of discharge or charge. Measured in mW.
    pub fn energy_rate(self, energy_rate: f64) -> Self {
        Self {
            builder: self.builder.property("energy-rate", energy_rate),
        }
    }

    /// If the device has history data that might be useful.
    pub fn has_history(self, has_history: bool) -> Self {
        Self {
            builder: self.builder.property("has-history", has_history),
        }
    }

    /// If the device has statistics data that might be useful.
    pub fn has_statistics(self, has_statistics: bool) -> Self {
        Self {
            builder: self.builder.property("has-statistics", has_statistics),
        }
    }

    /// The icon name, following the Icon Naming Specification
    pub fn icon_name(self, icon_name: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("icon-name", icon_name.into()),
        }
    }

    /// If the device is present, as some devices like laptop batteries
    /// can be removed, leaving an empty bay that is still technically a
    /// device.
    pub fn present(self, is_present: bool) -> Self {
        Self {
            builder: self.builder.property("is-present", is_present),
        }
    }

    /// If the device has a rechargeable battery.
    pub fn rechargeable(self, is_rechargeable: bool) -> Self {
        Self {
            builder: self.builder.property("is-rechargeable", is_rechargeable),
        }
    }

    /// The device kind, e.g. [`DeviceKind::Keyboard`][crate::DeviceKind::Keyboard].
    pub fn kind(self, kind: u32) -> Self {
        Self {
            builder: self.builder.property("kind", kind),
        }
    }

    /// The current luminosity of the device.
    pub fn luminosity(self, luminosity: f64) -> Self {
        Self {
            builder: self.builder.property("luminosity", luminosity),
        }
    }

    /// The model of the device.
    pub fn model(self, model: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("model", model.into()),
        }
    }

    /// The native path of the device, useful for direct device access.
    pub fn native_path(self, native_path: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("native-path", native_path.into()),
        }
    }

    /// If the device is online, i.e. connected.
    pub fn online(self, online: bool) -> Self {
        Self {
            builder: self.builder.property("online", online),
        }
    }

    /// The percentage charge of the device. Note that if the battery level property
    /// is something other than [`DeviceLevel::None`][crate::DeviceLevel::None], then this percentage is an
    /// approximation, and should not be used a number to display to the user.
    pub fn percentage(self, percentage: f64) -> Self {
        Self {
            builder: self.builder.property("percentage", percentage),
        }
    }

    /// If the device is powering the system.
    pub fn power_supply(self, power_supply: bool) -> Self {
        Self {
            builder: self.builder.property("power-supply", power_supply),
        }
    }

    /// The serial number of the device.
    pub fn serial(self, serial: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("serial", serial.into()),
        }
    }

    /// The state the device is in at this time, e.g. [`DeviceState::Empty`][crate::DeviceState::Empty].
    pub fn state(self, state: u32) -> Self {
        Self {
            builder: self.builder.property("state", state),
        }
    }

    /// The battery technology e.g. [`DeviceTechnology::LithiumIon`][crate::DeviceTechnology::LithiumIon].
    pub fn technology(self, technology: u32) -> Self {
        Self {
            builder: self.builder.property("technology", technology),
        }
    }

    /// The temperature of the device in degrees Celsius.
    pub fn temperature(self, temperature: f64) -> Self {
        Self {
            builder: self.builder.property("temperature", temperature),
        }
    }

    /// The amount of time until the device is empty.
    pub fn time_to_empty(self, time_to_empty: i64) -> Self {
        Self {
            builder: self.builder.property("time-to-empty", time_to_empty),
        }
    }

    /// The amount of time until the device is fully charged.
    pub fn time_to_full(self, time_to_full: i64) -> Self {
        Self {
            builder: self.builder.property("time-to-full", time_to_full),
        }
    }

    /// The last time the device was updated.
    pub fn update_time(self, update_time: u64) -> Self {
        Self {
            builder: self.builder.property("update-time", update_time),
        }
    }

    /// The vendor of the device.
    pub fn vendor(self, vendor: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("vendor", vendor.into()),
        }
    }

    /// The current voltage of the device.
    pub fn voltage(self, voltage: f64) -> Self {
        Self {
            builder: self.builder.property("voltage", voltage),
        }
    }

    pub fn voltage_max_design(self, voltage_max_design: f64) -> Self {
        Self {
            builder: self
                .builder
                .property("voltage-max-design", voltage_max_design),
        }
    }

    pub fn voltage_min_design(self, voltage_min_design: f64) -> Self {
        Self {
            builder: self
                .builder
                .property("voltage-min-design", voltage_min_design),
        }
    }

    /// The warning level e.g. [`DeviceLevel::Critical`][crate::DeviceLevel::Critical].
    pub fn warning_level(self, warning_level: u32) -> Self {
        Self {
            builder: self.builder.property("warning-level", warning_level),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`Device`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Device {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}

/// Trait containing all [`struct@Device`] methods.
///
/// # Implementors
///
/// [`Device`][struct@crate::Device]
pub trait DeviceExt: IsA<Device> + 'static {
    /// Gets the device history.
    /// ## `type_`
    /// The type of history, known values are "rate" and "charge".
    /// ## `timespec`
    /// the amount of time to look back into time.
    /// ## `resolution`
    /// the resolution of data.
    /// ## `cancellable`
    /// a [`gio::Cancellable`][crate::gio::Cancellable] or [`None`]
    ///
    /// # Returns
    ///
    /// an array of [`HistoryItem`][crate::HistoryItem]'s, with the most
    ///  recent one being first; [`None`] if `error` is set or `self` is
    ///  invalid
    #[doc(alias = "up_device_get_history_sync")]
    #[doc(alias = "get_history_sync")]
    fn history_sync(
        &self,
        type_: &str,
        timespec: u32,
        resolution: u32,
        cancellable: Option<&impl IsA<gio::Cancellable>>,
    ) -> Result<Vec<HistoryItem>, glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let ret = ffi::up_device_get_history_sync(
                self.as_ref().to_glib_none().0,
                type_.to_glib_none().0,
                timespec,
                resolution,
                cancellable.map(|p| p.as_ref()).to_glib_none().0,
                &mut error,
            );
            if error.is_null() {
                Ok(FromGlibPtrContainer::from_glib_full(ret))
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    /// Gets the object path for the device.
    ///
    /// # Returns
    ///
    /// the object path, or [`None`]
    #[doc(alias = "up_device_get_object_path")]
    #[doc(alias = "get_object_path")]
    fn object_path(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::up_device_get_object_path(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Gets the device current statistics.
    /// ## `type_`
    /// the type of statistics.
    /// ## `cancellable`
    /// a [`gio::Cancellable`][crate::gio::Cancellable] or [`None`]
    ///
    /// # Returns
    ///
    /// an array of [`StatsItem`][crate::StatsItem]'s, else [`None`] and `error` is used
    #[doc(alias = "up_device_get_statistics_sync")]
    #[doc(alias = "get_statistics_sync")]
    fn statistics_sync(
        &self,
        type_: &str,
        cancellable: Option<&impl IsA<gio::Cancellable>>,
    ) -> Result<Vec<StatsItem>, glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let ret = ffi::up_device_get_statistics_sync(
                self.as_ref().to_glib_none().0,
                type_.to_glib_none().0,
                cancellable.map(|p| p.as_ref()).to_glib_none().0,
                &mut error,
            );
            if error.is_null() {
                Ok(FromGlibPtrContainer::from_glib_full(ret))
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    /// Refreshes properties on the device.
    /// This function is normally not required and will only return without
    /// an error if the daemon was started in debug mode.
    /// ## `cancellable`
    /// a [`gio::Cancellable`][crate::gio::Cancellable] or [`None`]
    ///
    /// # Returns
    ///
    /// [`true`] for success, else [`false`] and `error` is used
    #[doc(alias = "up_device_refresh_sync")]
    fn refresh_sync(
        &self,
        cancellable: Option<&impl IsA<gio::Cancellable>>,
    ) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::up_device_refresh_sync(
                self.as_ref().to_glib_none().0,
                cancellable.map(|p| p.as_ref()).to_glib_none().0,
                &mut error,
            );
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    /// Sets the object path of the object and fills up initial properties.
    /// ## `object_path`
    /// The UPower object path.
    /// ## `cancellable`
    /// a [`gio::Cancellable`][crate::gio::Cancellable] or [`None`]
    ///
    /// # Returns
    ///
    /// [`true`] for success, else [`false`] and `error` is used
    #[doc(alias = "up_device_set_object_path_sync")]
    fn set_object_path_sync(
        &self,
        object_path: &str,
        cancellable: Option<&impl IsA<gio::Cancellable>>,
    ) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::up_device_set_object_path_sync(
                self.as_ref().to_glib_none().0,
                object_path.to_glib_none().0,
                cancellable.map(|p| p.as_ref()).to_glib_none().0,
                &mut error,
            );
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    /// Converts the device to a string description.
    ///
    /// # Returns
    ///
    /// text representation of [`Device`][crate::Device]
    #[doc(alias = "up_device_to_text")]
    fn to_text(&self) -> Option<glib::GString> {
        unsafe { from_glib_full(ffi::up_device_to_text(self.as_ref().to_glib_none().0)) }
    }

    /// The battery level, e.g. [`DeviceLevel::Critical`][crate::DeviceLevel::Critical]. If this is something
    /// other than [`DeviceLevel::None`][crate::DeviceLevel::None], then User Interfaces should use this
    /// approximate level instead of percentages.
    #[doc(alias = "battery-level")]
    fn battery_level(&self) -> u32 {
        ObjectExt::property(self.as_ref(), "battery-level")
    }

    /// The battery level, e.g. [`DeviceLevel::Critical`][crate::DeviceLevel::Critical]. If this is something
    /// other than [`DeviceLevel::None`][crate::DeviceLevel::None], then User Interfaces should use this
    /// approximate level instead of percentages.
    #[doc(alias = "battery-level")]
    fn set_battery_level(&self, battery_level: u32) {
        ObjectExt::set_property(self.as_ref(), "battery-level", battery_level)
    }

    /// The percentage capacity of the device where 100% means the device has
    /// the same charge potential as when it was manufactured.
    fn capacity(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "capacity")
    }

    /// The percentage capacity of the device where 100% means the device has
    /// the same charge potential as when it was manufactured.
    fn set_capacity(&self, capacity: f64) {
        ObjectExt::set_property(self.as_ref(), "capacity", capacity)
    }

    /// Coarse representation of battery capacity. The value is one of the following:
    /// Unknown, Critical, Low, Normal, High, and Full.
    #[doc(alias = "capacity-level")]
    fn capacity_level(&self) -> Option<glib::GString> {
        ObjectExt::property(self.as_ref(), "capacity-level")
    }

    /// Coarse representation of battery capacity. The value is one of the following:
    /// Unknown, Critical, Low, Normal, High, and Full.
    #[doc(alias = "capacity-level")]
    fn set_capacity_level(&self, capacity_level: Option<&str>) {
        ObjectExt::set_property(self.as_ref(), "capacity-level", capacity_level)
    }

    /// The number of charge cycles for the battery, or -1 if unknown
    /// or non-applicable.
    #[doc(alias = "charge-cycles")]
    fn charge_cycles(&self) -> i32 {
        ObjectExt::property(self.as_ref(), "charge-cycles")
    }

    /// The number of charge cycles for the battery, or -1 if unknown
    /// or non-applicable.
    #[doc(alias = "charge-cycles")]
    fn set_charge_cycles(&self, charge_cycles: i32) {
        ObjectExt::set_property(self.as_ref(), "charge-cycles", charge_cycles)
    }

    /// The charge end threshold of a battery.
    #[doc(alias = "charge-end-threshold")]
    fn charge_end_threshold(&self) -> u32 {
        ObjectExt::property(self.as_ref(), "charge-end-threshold")
    }

    /// The charge end threshold of a battery.
    #[doc(alias = "charge-end-threshold")]
    fn set_charge_end_threshold(&self, charge_end_threshold: u32) {
        ObjectExt::set_property(self.as_ref(), "charge-end-threshold", charge_end_threshold)
    }

    /// The charge start threshold of a battery.
    #[doc(alias = "charge-start-threshold")]
    fn charge_start_threshold(&self) -> u32 {
        ObjectExt::property(self.as_ref(), "charge-start-threshold")
    }

    /// The charge start threshold of a battery.
    #[doc(alias = "charge-start-threshold")]
    fn set_charge_start_threshold(&self, charge_start_threshold: u32) {
        ObjectExt::set_property(
            self.as_ref(),
            "charge-start-threshold",
            charge_start_threshold,
        )
    }

    /// The charge threshold of a battery is enabled, or false if unknown
    /// or non-applicable.
    #[doc(alias = "charge-threshold-enabled")]
    fn is_charge_threshold_enabled(&self) -> bool {
        ObjectExt::property(self.as_ref(), "charge-threshold-enabled")
    }

    /// The charge threshold of a battery is enabled, or false if unknown
    /// or non-applicable.
    #[doc(alias = "charge-threshold-enabled")]
    fn set_charge_threshold_enabled(&self, charge_threshold_enabled: bool) {
        ObjectExt::set_property(
            self.as_ref(),
            "charge-threshold-enabled",
            charge_threshold_enabled,
        )
    }

    /// The charge threshold of a battery is supported, or false if unknown
    /// or non-applicable.
    #[doc(alias = "charge-threshold-supported")]
    fn is_charge_threshold_supported(&self) -> bool {
        ObjectExt::property(self.as_ref(), "charge-threshold-supported")
    }

    /// The charge threshold of a battery is supported, or false if unknown
    /// or non-applicable.
    #[doc(alias = "charge-threshold-supported")]
    fn set_charge_threshold_supported(&self, charge_threshold_supported: bool) {
        ObjectExt::set_property(
            self.as_ref(),
            "charge-threshold-supported",
            charge_threshold_supported,
        )
    }

    /// The energy left in the device. Measured in mWh.
    fn energy(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "energy")
    }

    /// The energy left in the device. Measured in mWh.
    fn set_energy(&self, energy: f64) {
        ObjectExt::set_property(self.as_ref(), "energy", energy)
    }

    /// The energy the device will have when it is empty. This is usually zero.
    /// Measured in mWh.
    #[doc(alias = "energy-empty")]
    fn energy_empty(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "energy-empty")
    }

    /// The energy the device will have when it is empty. This is usually zero.
    /// Measured in mWh.
    #[doc(alias = "energy-empty")]
    fn set_energy_empty(&self, energy_empty: f64) {
        ObjectExt::set_property(self.as_ref(), "energy-empty", energy_empty)
    }

    /// The amount of energy when the device is fully charged. Measured in mWh.
    #[doc(alias = "energy-full")]
    fn energy_full(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "energy-full")
    }

    /// The amount of energy when the device is fully charged. Measured in mWh.
    #[doc(alias = "energy-full")]
    fn set_energy_full(&self, energy_full: f64) {
        ObjectExt::set_property(self.as_ref(), "energy-full", energy_full)
    }

    /// The amount of energy when the device was brand new. Measured in mWh.
    #[doc(alias = "energy-full-design")]
    fn energy_full_design(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "energy-full-design")
    }

    /// The amount of energy when the device was brand new. Measured in mWh.
    #[doc(alias = "energy-full-design")]
    fn set_energy_full_design(&self, energy_full_design: f64) {
        ObjectExt::set_property(self.as_ref(), "energy-full-design", energy_full_design)
    }

    /// The rate of discharge or charge. Measured in mW.
    #[doc(alias = "energy-rate")]
    fn energy_rate(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "energy-rate")
    }

    /// The rate of discharge or charge. Measured in mW.
    #[doc(alias = "energy-rate")]
    fn set_energy_rate(&self, energy_rate: f64) {
        ObjectExt::set_property(self.as_ref(), "energy-rate", energy_rate)
    }

    /// If the device has history data that might be useful.
    #[doc(alias = "has-history")]
    fn has_history(&self) -> bool {
        ObjectExt::property(self.as_ref(), "has-history")
    }

    /// If the device has history data that might be useful.
    #[doc(alias = "has-history")]
    fn set_has_history(&self, has_history: bool) {
        ObjectExt::set_property(self.as_ref(), "has-history", has_history)
    }

    /// If the device has statistics data that might be useful.
    #[doc(alias = "has-statistics")]
    fn has_statistics(&self) -> bool {
        ObjectExt::property(self.as_ref(), "has-statistics")
    }

    /// If the device has statistics data that might be useful.
    #[doc(alias = "has-statistics")]
    fn set_has_statistics(&self, has_statistics: bool) {
        ObjectExt::set_property(self.as_ref(), "has-statistics", has_statistics)
    }

    /// The icon name, following the Icon Naming Specification
    #[doc(alias = "icon-name")]
    fn icon_name(&self) -> Option<glib::GString> {
        ObjectExt::property(self.as_ref(), "icon-name")
    }

    /// The icon name, following the Icon Naming Specification
    #[doc(alias = "icon-name")]
    fn set_icon_name(&self, icon_name: Option<&str>) {
        ObjectExt::set_property(self.as_ref(), "icon-name", icon_name)
    }

    /// If the device is present, as some devices like laptop batteries
    /// can be removed, leaving an empty bay that is still technically a
    /// device.
    #[doc(alias = "is-present")]
    fn is_present(&self) -> bool {
        ObjectExt::property(self.as_ref(), "is-present")
    }

    /// If the device is present, as some devices like laptop batteries
    /// can be removed, leaving an empty bay that is still technically a
    /// device.
    #[doc(alias = "is-present")]
    fn set_is_present(&self, is_present: bool) {
        ObjectExt::set_property(self.as_ref(), "is-present", is_present)
    }

    /// If the device has a rechargeable battery.
    #[doc(alias = "is-rechargeable")]
    fn is_rechargeable(&self) -> bool {
        ObjectExt::property(self.as_ref(), "is-rechargeable")
    }

    /// If the device has a rechargeable battery.
    #[doc(alias = "is-rechargeable")]
    fn set_is_rechargeable(&self, is_rechargeable: bool) {
        ObjectExt::set_property(self.as_ref(), "is-rechargeable", is_rechargeable)
    }

    /// The device kind, e.g. [`DeviceKind::Keyboard`][crate::DeviceKind::Keyboard].
    fn kind(&self) -> u32 {
        ObjectExt::property(self.as_ref(), "kind")
    }

    /// The device kind, e.g. [`DeviceKind::Keyboard`][crate::DeviceKind::Keyboard].
    fn set_kind(&self, kind: u32) {
        ObjectExt::set_property(self.as_ref(), "kind", kind)
    }

    /// The current luminosity of the device.
    fn luminosity(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "luminosity")
    }

    /// The current luminosity of the device.
    fn set_luminosity(&self, luminosity: f64) {
        ObjectExt::set_property(self.as_ref(), "luminosity", luminosity)
    }

    /// The model of the device.
    fn model(&self) -> Option<glib::GString> {
        ObjectExt::property(self.as_ref(), "model")
    }

    /// The model of the device.
    fn set_model(&self, model: Option<&str>) {
        ObjectExt::set_property(self.as_ref(), "model", model)
    }

    /// The native path of the device, useful for direct device access.
    #[doc(alias = "native-path")]
    fn native_path(&self) -> Option<glib::GString> {
        ObjectExt::property(self.as_ref(), "native-path")
    }

    /// The native path of the device, useful for direct device access.
    #[doc(alias = "native-path")]
    fn set_native_path(&self, native_path: Option<&str>) {
        ObjectExt::set_property(self.as_ref(), "native-path", native_path)
    }

    /// If the device is online, i.e. connected.
    fn is_online(&self) -> bool {
        ObjectExt::property(self.as_ref(), "online")
    }

    /// If the device is online, i.e. connected.
    fn set_online(&self, online: bool) {
        ObjectExt::set_property(self.as_ref(), "online", online)
    }

    /// The percentage charge of the device. Note that if the battery level property
    /// is something other than [`DeviceLevel::None`][crate::DeviceLevel::None], then this percentage is an
    /// approximation, and should not be used a number to display to the user.
    fn percentage(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "percentage")
    }

    /// The percentage charge of the device. Note that if the battery level property
    /// is something other than [`DeviceLevel::None`][crate::DeviceLevel::None], then this percentage is an
    /// approximation, and should not be used a number to display to the user.
    fn set_percentage(&self, percentage: f64) {
        ObjectExt::set_property(self.as_ref(), "percentage", percentage)
    }

    /// If the device is powering the system.
    #[doc(alias = "power-supply")]
    fn is_power_supply(&self) -> bool {
        ObjectExt::property(self.as_ref(), "power-supply")
    }

    /// If the device is powering the system.
    #[doc(alias = "power-supply")]
    fn set_power_supply(&self, power_supply: bool) {
        ObjectExt::set_property(self.as_ref(), "power-supply", power_supply)
    }

    /// The serial number of the device.
    fn serial(&self) -> Option<glib::GString> {
        ObjectExt::property(self.as_ref(), "serial")
    }

    /// The serial number of the device.
    fn set_serial(&self, serial: Option<&str>) {
        ObjectExt::set_property(self.as_ref(), "serial", serial)
    }

    /// The state the device is in at this time, e.g. [`DeviceState::Empty`][crate::DeviceState::Empty].
    fn state(&self) -> u32 {
        ObjectExt::property(self.as_ref(), "state")
    }

    /// The state the device is in at this time, e.g. [`DeviceState::Empty`][crate::DeviceState::Empty].
    fn set_state(&self, state: u32) {
        ObjectExt::set_property(self.as_ref(), "state", state)
    }

    /// The battery technology e.g. [`DeviceTechnology::LithiumIon`][crate::DeviceTechnology::LithiumIon].
    fn technology(&self) -> u32 {
        ObjectExt::property(self.as_ref(), "technology")
    }

    /// The battery technology e.g. [`DeviceTechnology::LithiumIon`][crate::DeviceTechnology::LithiumIon].
    fn set_technology(&self, technology: u32) {
        ObjectExt::set_property(self.as_ref(), "technology", technology)
    }

    /// The temperature of the device in degrees Celsius.
    fn temperature(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "temperature")
    }

    /// The temperature of the device in degrees Celsius.
    fn set_temperature(&self, temperature: f64) {
        ObjectExt::set_property(self.as_ref(), "temperature", temperature)
    }

    /// The amount of time until the device is empty.
    #[doc(alias = "time-to-empty")]
    fn time_to_empty(&self) -> i64 {
        ObjectExt::property(self.as_ref(), "time-to-empty")
    }

    /// The amount of time until the device is empty.
    #[doc(alias = "time-to-empty")]
    fn set_time_to_empty(&self, time_to_empty: i64) {
        ObjectExt::set_property(self.as_ref(), "time-to-empty", time_to_empty)
    }

    /// The amount of time until the device is fully charged.
    #[doc(alias = "time-to-full")]
    fn time_to_full(&self) -> i64 {
        ObjectExt::property(self.as_ref(), "time-to-full")
    }

    /// The amount of time until the device is fully charged.
    #[doc(alias = "time-to-full")]
    fn set_time_to_full(&self, time_to_full: i64) {
        ObjectExt::set_property(self.as_ref(), "time-to-full", time_to_full)
    }

    /// The last time the device was updated.
    #[doc(alias = "update-time")]
    fn update_time(&self) -> u64 {
        ObjectExt::property(self.as_ref(), "update-time")
    }

    /// The last time the device was updated.
    #[doc(alias = "update-time")]
    fn set_update_time(&self, update_time: u64) {
        ObjectExt::set_property(self.as_ref(), "update-time", update_time)
    }

    /// The vendor of the device.
    fn vendor(&self) -> Option<glib::GString> {
        ObjectExt::property(self.as_ref(), "vendor")
    }

    /// The vendor of the device.
    fn set_vendor(&self, vendor: Option<&str>) {
        ObjectExt::set_property(self.as_ref(), "vendor", vendor)
    }

    /// The current voltage of the device.
    fn voltage(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "voltage")
    }

    /// The current voltage of the device.
    fn set_voltage(&self, voltage: f64) {
        ObjectExt::set_property(self.as_ref(), "voltage", voltage)
    }

    #[doc(alias = "voltage-max-design")]
    fn voltage_max_design(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "voltage-max-design")
    }

    #[doc(alias = "voltage-max-design")]
    fn set_voltage_max_design(&self, voltage_max_design: f64) {
        ObjectExt::set_property(self.as_ref(), "voltage-max-design", voltage_max_design)
    }

    #[doc(alias = "voltage-min-design")]
    fn voltage_min_design(&self) -> f64 {
        ObjectExt::property(self.as_ref(), "voltage-min-design")
    }

    #[doc(alias = "voltage-min-design")]
    fn set_voltage_min_design(&self, voltage_min_design: f64) {
        ObjectExt::set_property(self.as_ref(), "voltage-min-design", voltage_min_design)
    }

    /// The warning level e.g. [`DeviceLevel::Critical`][crate::DeviceLevel::Critical].
    #[doc(alias = "warning-level")]
    fn warning_level(&self) -> u32 {
        ObjectExt::property(self.as_ref(), "warning-level")
    }

    /// The warning level e.g. [`DeviceLevel::Critical`][crate::DeviceLevel::Critical].
    #[doc(alias = "warning-level")]
    fn set_warning_level(&self, warning_level: u32) {
        ObjectExt::set_property(self.as_ref(), "warning-level", warning_level)
    }

    #[doc(alias = "battery-level")]
    fn connect_battery_level_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_battery_level_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::battery-level".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_battery_level_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "capacity")]
    fn connect_capacity_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_capacity_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::capacity".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_capacity_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "capacity-level")]
    fn connect_capacity_level_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_capacity_level_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::capacity-level".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_capacity_level_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "charge-cycles")]
    fn connect_charge_cycles_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_charge_cycles_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::charge-cycles".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_charge_cycles_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "charge-end-threshold")]
    fn connect_charge_end_threshold_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_charge_end_threshold_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::charge-end-threshold".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_charge_end_threshold_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "charge-start-threshold")]
    fn connect_charge_start_threshold_notify<F: Fn(&Self) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_charge_start_threshold_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::charge-start-threshold".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_charge_start_threshold_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "charge-threshold-enabled")]
    fn connect_charge_threshold_enabled_notify<F: Fn(&Self) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_charge_threshold_enabled_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::charge-threshold-enabled".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_charge_threshold_enabled_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "charge-threshold-supported")]
    fn connect_charge_threshold_supported_notify<F: Fn(&Self) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_charge_threshold_supported_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::charge-threshold-supported".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_charge_threshold_supported_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "energy")]
    fn connect_energy_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_energy_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::energy".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_energy_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "energy-empty")]
    fn connect_energy_empty_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_energy_empty_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::energy-empty".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_energy_empty_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "energy-full")]
    fn connect_energy_full_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_energy_full_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::energy-full".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_energy_full_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "energy-full-design")]
    fn connect_energy_full_design_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_energy_full_design_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::energy-full-design".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_energy_full_design_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "energy-rate")]
    fn connect_energy_rate_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_energy_rate_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::energy-rate".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_energy_rate_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "has-history")]
    fn connect_has_history_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_has_history_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::has-history".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_has_history_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "has-statistics")]
    fn connect_has_statistics_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_has_statistics_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::has-statistics".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_has_statistics_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "icon-name")]
    fn connect_icon_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_icon_name_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::icon-name".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_icon_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "is-present")]
    fn connect_is_present_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_is_present_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::is-present".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_is_present_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "is-rechargeable")]
    fn connect_is_rechargeable_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_is_rechargeable_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::is-rechargeable".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_is_rechargeable_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "kind")]
    fn connect_kind_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_kind_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::kind".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_kind_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "luminosity")]
    fn connect_luminosity_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_luminosity_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::luminosity".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_luminosity_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "model")]
    fn connect_model_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_model_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::model".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_model_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "native-path")]
    fn connect_native_path_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_native_path_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::native-path".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_native_path_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "online")]
    fn connect_online_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_online_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::online".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_online_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "percentage")]
    fn connect_percentage_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_percentage_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::percentage".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_percentage_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "power-supply")]
    fn connect_power_supply_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_power_supply_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::power-supply".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_power_supply_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "serial")]
    fn connect_serial_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_serial_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::serial".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_serial_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "state")]
    fn connect_state_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_state_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::state".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_state_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "technology")]
    fn connect_technology_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_technology_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::technology".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_technology_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "temperature")]
    fn connect_temperature_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_temperature_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::temperature".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_temperature_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "time-to-empty")]
    fn connect_time_to_empty_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_time_to_empty_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::time-to-empty".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_time_to_empty_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "time-to-full")]
    fn connect_time_to_full_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_time_to_full_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::time-to-full".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_time_to_full_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "update-time")]
    fn connect_update_time_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_update_time_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::update-time".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_update_time_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "vendor")]
    fn connect_vendor_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_vendor_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::vendor".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_vendor_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "voltage")]
    fn connect_voltage_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_voltage_trampoline<P: IsA<Device>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::voltage".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_voltage_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "voltage-max-design")]
    fn connect_voltage_max_design_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_voltage_max_design_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::voltage-max-design".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_voltage_max_design_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "voltage-min-design")]
    fn connect_voltage_min_design_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_voltage_min_design_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::voltage-min-design".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_voltage_min_design_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "warning-level")]
    fn connect_warning_level_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_warning_level_trampoline<
            P: IsA<Device>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::UpDevice,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(Device::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::warning-level".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_warning_level_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<Device>> DeviceExt for O {}
