// This file was generated by gir (https://github.com/gtk-rs/gir)
// from upower-gir-files
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

/// The device type.
#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "UpDeviceKind")]
pub enum DeviceKind {
    #[doc(alias = "UP_DEVICE_KIND_UNKNOWN")]
    Unknown,
    #[doc(alias = "UP_DEVICE_KIND_LINE_POWER")]
    LinePower,
    #[doc(alias = "UP_DEVICE_KIND_BATTERY")]
    Battery,
    #[doc(alias = "UP_DEVICE_KIND_UPS")]
    Ups,
    #[doc(alias = "UP_DEVICE_KIND_MONITOR")]
    Monitor,
    #[doc(alias = "UP_DEVICE_KIND_MOUSE")]
    Mouse,
    #[doc(alias = "UP_DEVICE_KIND_KEYBOARD")]
    Keyboard,
    #[doc(alias = "UP_DEVICE_KIND_PDA")]
    Pda,
    #[doc(alias = "UP_DEVICE_KIND_PHONE")]
    Phone,
    #[doc(alias = "UP_DEVICE_KIND_MEDIA_PLAYER")]
    MediaPlayer,
    #[doc(alias = "UP_DEVICE_KIND_TABLET")]
    Tablet,
    #[doc(alias = "UP_DEVICE_KIND_COMPUTER")]
    Computer,
    #[doc(alias = "UP_DEVICE_KIND_GAMING_INPUT")]
    GamingInput,
    #[doc(alias = "UP_DEVICE_KIND_PEN")]
    Pen,
    #[doc(alias = "UP_DEVICE_KIND_TOUCHPAD")]
    Touchpad,
    #[doc(alias = "UP_DEVICE_KIND_MODEM")]
    Modem,
    #[doc(alias = "UP_DEVICE_KIND_NETWORK")]
    Network,
    #[doc(alias = "UP_DEVICE_KIND_HEADSET")]
    Headset,
    #[doc(alias = "UP_DEVICE_KIND_SPEAKERS")]
    Speakers,
    #[doc(alias = "UP_DEVICE_KIND_HEADPHONES")]
    Headphones,
    #[doc(alias = "UP_DEVICE_KIND_VIDEO")]
    Video,
    #[doc(alias = "UP_DEVICE_KIND_OTHER_AUDIO")]
    OtherAudio,
    #[doc(alias = "UP_DEVICE_KIND_REMOTE_CONTROL")]
    RemoteControl,
    #[doc(alias = "UP_DEVICE_KIND_PRINTER")]
    Printer,
    #[doc(alias = "UP_DEVICE_KIND_SCANNER")]
    Scanner,
    #[doc(alias = "UP_DEVICE_KIND_CAMERA")]
    Camera,
    #[doc(alias = "UP_DEVICE_KIND_WEARABLE")]
    Wearable,
    #[doc(alias = "UP_DEVICE_KIND_TOY")]
    Toy,
    #[doc(alias = "UP_DEVICE_KIND_BLUETOOTH_GENERIC")]
    BluetoothGeneric,
    #[doc(alias = "UP_DEVICE_KIND_LAST")]
    Last,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for DeviceKind {
    type GlibType = ffi::UpDeviceKind;

    fn into_glib(self) -> ffi::UpDeviceKind {
        match self {
            Self::Unknown => ffi::UP_DEVICE_KIND_UNKNOWN,
            Self::LinePower => ffi::UP_DEVICE_KIND_LINE_POWER,
            Self::Battery => ffi::UP_DEVICE_KIND_BATTERY,
            Self::Ups => ffi::UP_DEVICE_KIND_UPS,
            Self::Monitor => ffi::UP_DEVICE_KIND_MONITOR,
            Self::Mouse => ffi::UP_DEVICE_KIND_MOUSE,
            Self::Keyboard => ffi::UP_DEVICE_KIND_KEYBOARD,
            Self::Pda => ffi::UP_DEVICE_KIND_PDA,
            Self::Phone => ffi::UP_DEVICE_KIND_PHONE,
            Self::MediaPlayer => ffi::UP_DEVICE_KIND_MEDIA_PLAYER,
            Self::Tablet => ffi::UP_DEVICE_KIND_TABLET,
            Self::Computer => ffi::UP_DEVICE_KIND_COMPUTER,
            Self::GamingInput => ffi::UP_DEVICE_KIND_GAMING_INPUT,
            Self::Pen => ffi::UP_DEVICE_KIND_PEN,
            Self::Touchpad => ffi::UP_DEVICE_KIND_TOUCHPAD,
            Self::Modem => ffi::UP_DEVICE_KIND_MODEM,
            Self::Network => ffi::UP_DEVICE_KIND_NETWORK,
            Self::Headset => ffi::UP_DEVICE_KIND_HEADSET,
            Self::Speakers => ffi::UP_DEVICE_KIND_SPEAKERS,
            Self::Headphones => ffi::UP_DEVICE_KIND_HEADPHONES,
            Self::Video => ffi::UP_DEVICE_KIND_VIDEO,
            Self::OtherAudio => ffi::UP_DEVICE_KIND_OTHER_AUDIO,
            Self::RemoteControl => ffi::UP_DEVICE_KIND_REMOTE_CONTROL,
            Self::Printer => ffi::UP_DEVICE_KIND_PRINTER,
            Self::Scanner => ffi::UP_DEVICE_KIND_SCANNER,
            Self::Camera => ffi::UP_DEVICE_KIND_CAMERA,
            Self::Wearable => ffi::UP_DEVICE_KIND_WEARABLE,
            Self::Toy => ffi::UP_DEVICE_KIND_TOY,
            Self::BluetoothGeneric => ffi::UP_DEVICE_KIND_BLUETOOTH_GENERIC,
            Self::Last => ffi::UP_DEVICE_KIND_LAST,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::UpDeviceKind> for DeviceKind {
    unsafe fn from_glib(value: ffi::UpDeviceKind) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::UP_DEVICE_KIND_UNKNOWN => Self::Unknown,
            ffi::UP_DEVICE_KIND_LINE_POWER => Self::LinePower,
            ffi::UP_DEVICE_KIND_BATTERY => Self::Battery,
            ffi::UP_DEVICE_KIND_UPS => Self::Ups,
            ffi::UP_DEVICE_KIND_MONITOR => Self::Monitor,
            ffi::UP_DEVICE_KIND_MOUSE => Self::Mouse,
            ffi::UP_DEVICE_KIND_KEYBOARD => Self::Keyboard,
            ffi::UP_DEVICE_KIND_PDA => Self::Pda,
            ffi::UP_DEVICE_KIND_PHONE => Self::Phone,
            ffi::UP_DEVICE_KIND_MEDIA_PLAYER => Self::MediaPlayer,
            ffi::UP_DEVICE_KIND_TABLET => Self::Tablet,
            ffi::UP_DEVICE_KIND_COMPUTER => Self::Computer,
            ffi::UP_DEVICE_KIND_GAMING_INPUT => Self::GamingInput,
            ffi::UP_DEVICE_KIND_PEN => Self::Pen,
            ffi::UP_DEVICE_KIND_TOUCHPAD => Self::Touchpad,
            ffi::UP_DEVICE_KIND_MODEM => Self::Modem,
            ffi::UP_DEVICE_KIND_NETWORK => Self::Network,
            ffi::UP_DEVICE_KIND_HEADSET => Self::Headset,
            ffi::UP_DEVICE_KIND_SPEAKERS => Self::Speakers,
            ffi::UP_DEVICE_KIND_HEADPHONES => Self::Headphones,
            ffi::UP_DEVICE_KIND_VIDEO => Self::Video,
            ffi::UP_DEVICE_KIND_OTHER_AUDIO => Self::OtherAudio,
            ffi::UP_DEVICE_KIND_REMOTE_CONTROL => Self::RemoteControl,
            ffi::UP_DEVICE_KIND_PRINTER => Self::Printer,
            ffi::UP_DEVICE_KIND_SCANNER => Self::Scanner,
            ffi::UP_DEVICE_KIND_CAMERA => Self::Camera,
            ffi::UP_DEVICE_KIND_WEARABLE => Self::Wearable,
            ffi::UP_DEVICE_KIND_TOY => Self::Toy,
            ffi::UP_DEVICE_KIND_BLUETOOTH_GENERIC => Self::BluetoothGeneric,
            ffi::UP_DEVICE_KIND_LAST => Self::Last,
            value => Self::__Unknown(value),
        }
    }
}

/// The level of a battery. Only values up to, and including
/// [`Action`][Self::Action] are relevant for the `WarningLevel`.
/// The `BatteryLevel` only uses the following values:
/// - [`Unknown`][Self::Unknown]
/// - [`None`][Self::None]
/// - [`Low`][Self::Low]
/// - [`Critical`][Self::Critical]
/// - [`Normal`][Self::Normal]
/// - [`High`][Self::High]
/// - [`Full`][Self::Full]
#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "UpDeviceLevel")]
pub enum DeviceLevel {
    #[doc(alias = "UP_DEVICE_LEVEL_UNKNOWN")]
    Unknown,
    #[doc(alias = "UP_DEVICE_LEVEL_NONE")]
    None,
    #[doc(alias = "UP_DEVICE_LEVEL_DISCHARGING")]
    Discharging,
    #[doc(alias = "UP_DEVICE_LEVEL_LOW")]
    Low,
    #[doc(alias = "UP_DEVICE_LEVEL_CRITICAL")]
    Critical,
    #[doc(alias = "UP_DEVICE_LEVEL_ACTION")]
    Action,
    #[doc(alias = "UP_DEVICE_LEVEL_NORMAL")]
    Normal,
    #[doc(alias = "UP_DEVICE_LEVEL_HIGH")]
    High,
    #[doc(alias = "UP_DEVICE_LEVEL_FULL")]
    Full,
    #[doc(alias = "UP_DEVICE_LEVEL_LAST")]
    Last,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for DeviceLevel {
    type GlibType = ffi::UpDeviceLevel;

    #[inline]
    fn into_glib(self) -> ffi::UpDeviceLevel {
        match self {
            Self::Unknown => ffi::UP_DEVICE_LEVEL_UNKNOWN,
            Self::None => ffi::UP_DEVICE_LEVEL_NONE,
            Self::Discharging => ffi::UP_DEVICE_LEVEL_DISCHARGING,
            Self::Low => ffi::UP_DEVICE_LEVEL_LOW,
            Self::Critical => ffi::UP_DEVICE_LEVEL_CRITICAL,
            Self::Action => ffi::UP_DEVICE_LEVEL_ACTION,
            Self::Normal => ffi::UP_DEVICE_LEVEL_NORMAL,
            Self::High => ffi::UP_DEVICE_LEVEL_HIGH,
            Self::Full => ffi::UP_DEVICE_LEVEL_FULL,
            Self::Last => ffi::UP_DEVICE_LEVEL_LAST,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::UpDeviceLevel> for DeviceLevel {
    #[inline]
    unsafe fn from_glib(value: ffi::UpDeviceLevel) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::UP_DEVICE_LEVEL_UNKNOWN => Self::Unknown,
            ffi::UP_DEVICE_LEVEL_NONE => Self::None,
            ffi::UP_DEVICE_LEVEL_DISCHARGING => Self::Discharging,
            ffi::UP_DEVICE_LEVEL_LOW => Self::Low,
            ffi::UP_DEVICE_LEVEL_CRITICAL => Self::Critical,
            ffi::UP_DEVICE_LEVEL_ACTION => Self::Action,
            ffi::UP_DEVICE_LEVEL_NORMAL => Self::Normal,
            ffi::UP_DEVICE_LEVEL_HIGH => Self::High,
            ffi::UP_DEVICE_LEVEL_FULL => Self::Full,
            ffi::UP_DEVICE_LEVEL_LAST => Self::Last,
            value => Self::__Unknown(value),
        }
    }
}

/// The device state.
#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "UpDeviceState")]
pub enum DeviceState {
    #[doc(alias = "UP_DEVICE_STATE_UNKNOWN")]
    Unknown,
    #[doc(alias = "UP_DEVICE_STATE_CHARGING")]
    Charging,
    #[doc(alias = "UP_DEVICE_STATE_DISCHARGING")]
    Discharging,
    #[doc(alias = "UP_DEVICE_STATE_EMPTY")]
    Empty,
    #[doc(alias = "UP_DEVICE_STATE_FULLY_CHARGED")]
    FullyCharged,
    #[doc(alias = "UP_DEVICE_STATE_PENDING_CHARGE")]
    PendingCharge,
    #[doc(alias = "UP_DEVICE_STATE_PENDING_DISCHARGE")]
    PendingDischarge,
    #[doc(alias = "UP_DEVICE_STATE_LAST")]
    Last,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for DeviceState {
    type GlibType = ffi::UpDeviceState;

    #[inline]
    fn into_glib(self) -> ffi::UpDeviceState {
        match self {
            Self::Unknown => ffi::UP_DEVICE_STATE_UNKNOWN,
            Self::Charging => ffi::UP_DEVICE_STATE_CHARGING,
            Self::Discharging => ffi::UP_DEVICE_STATE_DISCHARGING,
            Self::Empty => ffi::UP_DEVICE_STATE_EMPTY,
            Self::FullyCharged => ffi::UP_DEVICE_STATE_FULLY_CHARGED,
            Self::PendingCharge => ffi::UP_DEVICE_STATE_PENDING_CHARGE,
            Self::PendingDischarge => ffi::UP_DEVICE_STATE_PENDING_DISCHARGE,
            Self::Last => ffi::UP_DEVICE_STATE_LAST,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::UpDeviceState> for DeviceState {
    #[inline]
    unsafe fn from_glib(value: ffi::UpDeviceState) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::UP_DEVICE_STATE_UNKNOWN => Self::Unknown,
            ffi::UP_DEVICE_STATE_CHARGING => Self::Charging,
            ffi::UP_DEVICE_STATE_DISCHARGING => Self::Discharging,
            ffi::UP_DEVICE_STATE_EMPTY => Self::Empty,
            ffi::UP_DEVICE_STATE_FULLY_CHARGED => Self::FullyCharged,
            ffi::UP_DEVICE_STATE_PENDING_CHARGE => Self::PendingCharge,
            ffi::UP_DEVICE_STATE_PENDING_DISCHARGE => Self::PendingDischarge,
            ffi::UP_DEVICE_STATE_LAST => Self::Last,
            value => Self::__Unknown(value),
        }
    }
}

/// The device technology.
#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[non_exhaustive]
#[doc(alias = "UpDeviceTechnology")]
pub enum DeviceTechnology {
    #[doc(alias = "UP_DEVICE_TECHNOLOGY_UNKNOWN")]
    Unknown,
    #[doc(alias = "UP_DEVICE_TECHNOLOGY_LITHIUM_ION")]
    LithiumIon,
    #[doc(alias = "UP_DEVICE_TECHNOLOGY_LITHIUM_POLYMER")]
    LithiumPolymer,
    #[doc(alias = "UP_DEVICE_TECHNOLOGY_LITHIUM_IRON_PHOSPHATE")]
    LithiumIronPhosphate,
    #[doc(alias = "UP_DEVICE_TECHNOLOGY_LEAD_ACID")]
    LeadAcid,
    #[doc(alias = "UP_DEVICE_TECHNOLOGY_NICKEL_CADMIUM")]
    NickelCadmium,
    #[doc(alias = "UP_DEVICE_TECHNOLOGY_NICKEL_METAL_HYDRIDE")]
    NickelMetalHydride,
    #[doc(alias = "UP_DEVICE_TECHNOLOGY_LAST")]
    Last,
    #[doc(hidden)]
    __Unknown(i32),
}

#[doc(hidden)]
impl IntoGlib for DeviceTechnology {
    type GlibType = ffi::UpDeviceTechnology;

    #[inline]
    fn into_glib(self) -> ffi::UpDeviceTechnology {
        match self {
            Self::Unknown => ffi::UP_DEVICE_TECHNOLOGY_UNKNOWN,
            Self::LithiumIon => ffi::UP_DEVICE_TECHNOLOGY_LITHIUM_ION,
            Self::LithiumPolymer => ffi::UP_DEVICE_TECHNOLOGY_LITHIUM_POLYMER,
            Self::LithiumIronPhosphate => ffi::UP_DEVICE_TECHNOLOGY_LITHIUM_IRON_PHOSPHATE,
            Self::LeadAcid => ffi::UP_DEVICE_TECHNOLOGY_LEAD_ACID,
            Self::NickelCadmium => ffi::UP_DEVICE_TECHNOLOGY_NICKEL_CADMIUM,
            Self::NickelMetalHydride => ffi::UP_DEVICE_TECHNOLOGY_NICKEL_METAL_HYDRIDE,
            Self::Last => ffi::UP_DEVICE_TECHNOLOGY_LAST,
            Self::__Unknown(value) => value,
        }
    }
}

#[doc(hidden)]
impl FromGlib<ffi::UpDeviceTechnology> for DeviceTechnology {
    #[inline]
    unsafe fn from_glib(value: ffi::UpDeviceTechnology) -> Self {
        skip_assert_initialized!();

        match value {
            ffi::UP_DEVICE_TECHNOLOGY_UNKNOWN => Self::Unknown,
            ffi::UP_DEVICE_TECHNOLOGY_LITHIUM_ION => Self::LithiumIon,
            ffi::UP_DEVICE_TECHNOLOGY_LITHIUM_POLYMER => Self::LithiumPolymer,
            ffi::UP_DEVICE_TECHNOLOGY_LITHIUM_IRON_PHOSPHATE => Self::LithiumIronPhosphate,
            ffi::UP_DEVICE_TECHNOLOGY_LEAD_ACID => Self::LeadAcid,
            ffi::UP_DEVICE_TECHNOLOGY_NICKEL_CADMIUM => Self::NickelCadmium,
            ffi::UP_DEVICE_TECHNOLOGY_NICKEL_METAL_HYDRIDE => Self::NickelMetalHydride,
            ffi::UP_DEVICE_TECHNOLOGY_LAST => Self::Last,
            value => Self::__Unknown(value),
        }
    }
}
