// This file was generated by gir (https://github.com/gtk-rs/gir)
// from upower-gir-files
// DO NOT EDIT

use crate::{DeviceState, ffi};
use glib::{
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    ///
    ///
    /// ## Properties
    ///
    ///
    /// #### `state`
    ///  Readable | Writeable
    ///
    ///
    /// #### `time`
    ///  Readable | Writeable
    ///
    ///
    /// #### `value`
    ///  Readable | Writeable
    ///
    /// # Implements
    ///
    /// [`HistoryItemExt`][trait@crate::prelude::HistoryItemExt]
    #[doc(alias = "UpHistoryItem")]
    pub struct HistoryItem(Object<ffi::UpHistoryItem, ffi::UpHistoryItemClass>);

    match fn {
        type_ => || ffi::up_history_item_get_type(),
    }
}

impl HistoryItem {
    pub const NONE: Option<&'static HistoryItem> = None;

    ///
    /// # Returns
    ///
    /// a new UpHistoryItem object.
    #[doc(alias = "up_history_item_new")]
    pub fn new() -> HistoryItem {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::up_history_item_new()) }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`HistoryItem`] objects.
    ///
    /// This method returns an instance of [`HistoryItemBuilder`](crate::builders::HistoryItemBuilder) which can be used to create [`HistoryItem`] objects.
    pub fn builder() -> HistoryItemBuilder {
        HistoryItemBuilder::new()
    }
}

impl Default for HistoryItem {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for HistoryItem {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(&HistoryItemExt::to_str(self))
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`HistoryItem`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct HistoryItemBuilder {
    builder: glib::object::ObjectBuilder<'static, HistoryItem>,
}

impl HistoryItemBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn state(self, state: u32) -> Self {
        Self {
            builder: self.builder.property("state", state),
        }
    }

    pub fn time(self, time: u32) -> Self {
        Self {
            builder: self.builder.property("time", time),
        }
    }

    pub fn value(self, value: f64) -> Self {
        Self {
            builder: self.builder.property("value", value),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`HistoryItem`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> HistoryItem {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}

/// Trait containing all [`struct@HistoryItem`] methods.
///
/// # Implementors
///
/// [`HistoryItem`][struct@crate::HistoryItem]
pub trait HistoryItemExt: IsA<HistoryItem> + 'static {
    /// Gets the item state.
    #[doc(alias = "up_history_item_get_state")]
    #[doc(alias = "get_state")]
    fn state(&self) -> DeviceState {
        unsafe {
            from_glib(ffi::up_history_item_get_state(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    /// Gets the item time.
    #[doc(alias = "up_history_item_get_time")]
    #[doc(alias = "get_time")]
    fn time(&self) -> u32 {
        unsafe { ffi::up_history_item_get_time(self.as_ref().to_glib_none().0) }
    }

    /// Gets the item value.
    #[doc(alias = "up_history_item_get_value")]
    #[doc(alias = "get_value")]
    fn value(&self) -> f64 {
        unsafe { ffi::up_history_item_get_value(self.as_ref().to_glib_none().0) }
    }

    /// Converts the history item to a string representation.
    #[doc(alias = "up_history_item_set_from_string")]
    fn set_from_string(&self, text: &str) -> bool {
        unsafe {
            from_glib(ffi::up_history_item_set_from_string(
                self.as_ref().to_glib_none().0,
                text.to_glib_none().0,
            ))
        }
    }

    /// Sets the item state.
    /// ## `state`
    /// the new value
    #[doc(alias = "up_history_item_set_state")]
    #[doc(alias = "state")]
    fn set_state(&self, state: DeviceState) {
        unsafe {
            ffi::up_history_item_set_state(self.as_ref().to_glib_none().0, state.into_glib());
        }
    }

    /// Sets the item time.
    /// ## `time`
    /// the new value
    #[doc(alias = "up_history_item_set_time")]
    #[doc(alias = "time")]
    fn set_time(&self, time: u32) {
        unsafe {
            ffi::up_history_item_set_time(self.as_ref().to_glib_none().0, time);
        }
    }

    /// Sets the item time to the present value.
    #[doc(alias = "up_history_item_set_time_to_present")]
    fn set_time_to_present(&self) {
        unsafe {
            ffi::up_history_item_set_time_to_present(self.as_ref().to_glib_none().0);
        }
    }

    /// Sets the item value.
    /// ## `value`
    /// the new value
    #[doc(alias = "up_history_item_set_value")]
    #[doc(alias = "value")]
    fn set_value(&self, value: f64) {
        unsafe {
            ffi::up_history_item_set_value(self.as_ref().to_glib_none().0, value);
        }
    }

    /// Converts the history item to a string representation.
    #[doc(alias = "up_history_item_to_string")]
    #[doc(alias = "to_string")]
    fn to_str(&self) -> glib::GString {
        unsafe {
            from_glib_full(ffi::up_history_item_to_string(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "state")]
    fn connect_state_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_state_trampoline<P: IsA<HistoryItem>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpHistoryItem,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(HistoryItem::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::state".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_state_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "time")]
    fn connect_time_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_time_trampoline<P: IsA<HistoryItem>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpHistoryItem,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(HistoryItem::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::time".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_time_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "value")]
    fn connect_value_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_value_trampoline<P: IsA<HistoryItem>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpHistoryItem,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(HistoryItem::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::value".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_value_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<HistoryItem>> HistoryItemExt for O {}
