// This file was generated by gir (https://github.com/gtk-rs/gir)
// from upower-gir-files
// DO NOT EDIT

mod client;
pub use self::client::Client;

mod device;
pub use self::device::Device;

mod history_item;
pub use self::history_item::HistoryItem;

mod stats_item;
pub use self::stats_item::StatsItem;

mod enums;
pub use self::enums::DeviceKind;
pub use self::enums::DeviceLevel;
pub use self::enums::DeviceState;
pub use self::enums::DeviceTechnology;

pub(crate) mod traits {
    pub use super::client::ClientExt;
    pub use super::device::DeviceExt;
    pub use super::history_item::HistoryItemExt;
    pub use super::stats_item::StatsItemExt;
}
pub(crate) mod builders {
    pub use super::device::DeviceBuilder;
    pub use super::history_item::HistoryItemBuilder;
    pub use super::stats_item::StatsItemBuilder;
}
