// This file was generated by gir (https://github.com/gtk-rs/gir)
// from upower-gir-files
// DO NOT EDIT

use crate::ffi;
use glib::{
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    ///
    ///
    /// ## Properties
    ///
    ///
    /// #### `accuracy`
    ///  Readable | Writeable
    ///
    ///
    /// #### `value`
    ///  Readable | Writeable
    ///
    /// # Implements
    ///
    /// [`StatsItemExt`][trait@crate::prelude::StatsItemExt]
    #[doc(alias = "UpStatsItem")]
    pub struct StatsItem(Object<ffi::UpStatsItem, ffi::UpStatsItemClass>);

    match fn {
        type_ => || ffi::up_stats_item_get_type(),
    }
}

impl StatsItem {
    pub const NONE: Option<&'static StatsItem> = None;

    ///
    /// # Returns
    ///
    /// a new UpStatsItem object.
    #[doc(alias = "up_stats_item_new")]
    pub fn new() -> StatsItem {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::up_stats_item_new()) }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`StatsItem`] objects.
    ///
    /// This method returns an instance of [`StatsItemBuilder`](crate::builders::StatsItemBuilder) which can be used to create [`StatsItem`] objects.
    pub fn builder() -> StatsItemBuilder {
        StatsItemBuilder::new()
    }
}

impl Default for StatsItem {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`StatsItem`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct StatsItemBuilder {
    builder: glib::object::ObjectBuilder<'static, StatsItem>,
}

impl StatsItemBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn accuracy(self, accuracy: f64) -> Self {
        Self {
            builder: self.builder.property("accuracy", accuracy),
        }
    }

    pub fn value(self, value: f64) -> Self {
        Self {
            builder: self.builder.property("value", value),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`StatsItem`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> StatsItem {
        assert_initialized_main_thread!();
        self.builder.build()
    }
}

/// Trait containing all [`struct@StatsItem`] methods.
///
/// # Implementors
///
/// [`StatsItem`][struct@crate::StatsItem]
pub trait StatsItemExt: IsA<StatsItem> + 'static {
    /// Gets the item accuracy.
    #[doc(alias = "up_stats_item_get_accuracy")]
    #[doc(alias = "get_accuracy")]
    fn accuracy(&self) -> f64 {
        unsafe { ffi::up_stats_item_get_accuracy(self.as_ref().to_glib_none().0) }
    }

    /// Gets the item value.
    #[doc(alias = "up_stats_item_get_value")]
    #[doc(alias = "get_value")]
    fn value(&self) -> f64 {
        unsafe { ffi::up_stats_item_get_value(self.as_ref().to_glib_none().0) }
    }

    /// Sets the item accuracy.
    #[doc(alias = "up_stats_item_set_accuracy")]
    #[doc(alias = "accuracy")]
    fn set_accuracy(&self, accuracy: f64) {
        unsafe {
            ffi::up_stats_item_set_accuracy(self.as_ref().to_glib_none().0, accuracy);
        }
    }

    /// Sets the item value.
    #[doc(alias = "up_stats_item_set_value")]
    #[doc(alias = "value")]
    fn set_value(&self, value: f64) {
        unsafe {
            ffi::up_stats_item_set_value(self.as_ref().to_glib_none().0, value);
        }
    }

    #[doc(alias = "accuracy")]
    fn connect_accuracy_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_accuracy_trampoline<P: IsA<StatsItem>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpStatsItem,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(StatsItem::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::accuracy".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_accuracy_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "value")]
    fn connect_value_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_value_trampoline<P: IsA<StatsItem>, F: Fn(&P) + 'static>(
            this: *mut ffi::UpStatsItem,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(StatsItem::from_glib_borrow(this).unsafe_cast_ref())
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::value".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_value_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<StatsItem>> StatsItemExt for O {}
