// This file was generated by gir (https://github.com/gtk-rs/gir)
// from upower-gir-files
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
#![allow(
    clippy::approx_constant,
    clippy::type_complexity,
    clippy::unreadable_literal,
    clippy::upper_case_acronyms
)]
#![cfg_attr(docsrs, feature(doc_cfg))]

use gio_sys as gio;
use glib_sys as glib;
use gobject_sys as gobject;

#[allow(unused_imports)]
use libc::{FILE, intptr_t, off_t, size_t, ssize_t, time_t, uintptr_t};
#[cfg(unix)]
#[allow(unused_imports)]
use libc::{dev_t, gid_t, pid_t, socklen_t, uid_t};
#[allow(unused_imports)]
use std::ffi::{
    c_char, c_double, c_float, c_int, c_long, c_short, c_uchar, c_uint, c_ulong, c_ushort, c_void,
};

#[allow(unused_imports)]
use glib::{GType, gboolean, gconstpointer, gpointer};

// Enums
pub type UpDeviceKind = c_int;
pub const UP_DEVICE_KIND_UNKNOWN: UpDeviceKind = 0;
pub const UP_DEVICE_KIND_LINE_POWER: UpDeviceKind = 1;
pub const UP_DEVICE_KIND_BATTERY: UpDeviceKind = 2;
pub const UP_DEVICE_KIND_UPS: UpDeviceKind = 3;
pub const UP_DEVICE_KIND_MONITOR: UpDeviceKind = 4;
pub const UP_DEVICE_KIND_MOUSE: UpDeviceKind = 5;
pub const UP_DEVICE_KIND_KEYBOARD: UpDeviceKind = 6;
pub const UP_DEVICE_KIND_PDA: UpDeviceKind = 7;
pub const UP_DEVICE_KIND_PHONE: UpDeviceKind = 8;
pub const UP_DEVICE_KIND_MEDIA_PLAYER: UpDeviceKind = 9;
pub const UP_DEVICE_KIND_TABLET: UpDeviceKind = 10;
pub const UP_DEVICE_KIND_COMPUTER: UpDeviceKind = 11;
pub const UP_DEVICE_KIND_GAMING_INPUT: UpDeviceKind = 12;
pub const UP_DEVICE_KIND_PEN: UpDeviceKind = 13;
pub const UP_DEVICE_KIND_TOUCHPAD: UpDeviceKind = 14;
pub const UP_DEVICE_KIND_MODEM: UpDeviceKind = 15;
pub const UP_DEVICE_KIND_NETWORK: UpDeviceKind = 16;
pub const UP_DEVICE_KIND_HEADSET: UpDeviceKind = 17;
pub const UP_DEVICE_KIND_SPEAKERS: UpDeviceKind = 18;
pub const UP_DEVICE_KIND_HEADPHONES: UpDeviceKind = 19;
pub const UP_DEVICE_KIND_VIDEO: UpDeviceKind = 20;
pub const UP_DEVICE_KIND_OTHER_AUDIO: UpDeviceKind = 21;
pub const UP_DEVICE_KIND_REMOTE_CONTROL: UpDeviceKind = 22;
pub const UP_DEVICE_KIND_PRINTER: UpDeviceKind = 23;
pub const UP_DEVICE_KIND_SCANNER: UpDeviceKind = 24;
pub const UP_DEVICE_KIND_CAMERA: UpDeviceKind = 25;
pub const UP_DEVICE_KIND_WEARABLE: UpDeviceKind = 26;
pub const UP_DEVICE_KIND_TOY: UpDeviceKind = 27;
pub const UP_DEVICE_KIND_BLUETOOTH_GENERIC: UpDeviceKind = 28;
pub const UP_DEVICE_KIND_LAST: UpDeviceKind = 29;

pub type UpDeviceLevel = c_int;
pub const UP_DEVICE_LEVEL_UNKNOWN: UpDeviceLevel = 0;
pub const UP_DEVICE_LEVEL_NONE: UpDeviceLevel = 1;
pub const UP_DEVICE_LEVEL_DISCHARGING: UpDeviceLevel = 2;
pub const UP_DEVICE_LEVEL_LOW: UpDeviceLevel = 3;
pub const UP_DEVICE_LEVEL_CRITICAL: UpDeviceLevel = 4;
pub const UP_DEVICE_LEVEL_ACTION: UpDeviceLevel = 5;
pub const UP_DEVICE_LEVEL_NORMAL: UpDeviceLevel = 6;
pub const UP_DEVICE_LEVEL_HIGH: UpDeviceLevel = 7;
pub const UP_DEVICE_LEVEL_FULL: UpDeviceLevel = 8;
pub const UP_DEVICE_LEVEL_LAST: UpDeviceLevel = 9;

pub type UpDeviceState = c_int;
pub const UP_DEVICE_STATE_UNKNOWN: UpDeviceState = 0;
pub const UP_DEVICE_STATE_CHARGING: UpDeviceState = 1;
pub const UP_DEVICE_STATE_DISCHARGING: UpDeviceState = 2;
pub const UP_DEVICE_STATE_EMPTY: UpDeviceState = 3;
pub const UP_DEVICE_STATE_FULLY_CHARGED: UpDeviceState = 4;
pub const UP_DEVICE_STATE_PENDING_CHARGE: UpDeviceState = 5;
pub const UP_DEVICE_STATE_PENDING_DISCHARGE: UpDeviceState = 6;
pub const UP_DEVICE_STATE_LAST: UpDeviceState = 7;

pub type UpDeviceTechnology = c_int;
pub const UP_DEVICE_TECHNOLOGY_UNKNOWN: UpDeviceTechnology = 0;
pub const UP_DEVICE_TECHNOLOGY_LITHIUM_ION: UpDeviceTechnology = 1;
pub const UP_DEVICE_TECHNOLOGY_LITHIUM_POLYMER: UpDeviceTechnology = 2;
pub const UP_DEVICE_TECHNOLOGY_LITHIUM_IRON_PHOSPHATE: UpDeviceTechnology = 3;
pub const UP_DEVICE_TECHNOLOGY_LEAD_ACID: UpDeviceTechnology = 4;
pub const UP_DEVICE_TECHNOLOGY_NICKEL_CADMIUM: UpDeviceTechnology = 5;
pub const UP_DEVICE_TECHNOLOGY_NICKEL_METAL_HYDRIDE: UpDeviceTechnology = 6;
pub const UP_DEVICE_TECHNOLOGY_LAST: UpDeviceTechnology = 7;

// Constants
pub const UP_MAJOR_VERSION: c_int = 1;
pub const UP_MICRO_VERSION: c_int = 0;
pub const UP_MINOR_VERSION: c_int = 91;

// Records
#[derive(Copy, Clone)]
#[repr(C)]
pub struct UpClientClass {
    pub parent_class: gobject::GObjectClass,
    pub device_added: Option<unsafe extern "C" fn(*mut UpClient, *mut UpDevice)>,
    pub device_removed: Option<unsafe extern "C" fn(*mut UpClient, *const c_char)>,
    pub _up_client_reserved1: Option<unsafe extern "C" fn()>,
    pub _up_client_reserved2: Option<unsafe extern "C" fn()>,
    pub _up_client_reserved3: Option<unsafe extern "C" fn()>,
    pub _up_client_reserved4: Option<unsafe extern "C" fn()>,
    pub _up_client_reserved5: Option<unsafe extern "C" fn()>,
    pub _up_client_reserved6: Option<unsafe extern "C" fn()>,
    pub _up_client_reserved7: Option<unsafe extern "C" fn()>,
    pub _up_client_reserved8: Option<unsafe extern "C" fn()>,
}

impl ::std::fmt::Debug for UpClientClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("UpClientClass @ {self:p}"))
            .field("device_added", &self.device_added)
            .field("device_removed", &self.device_removed)
            .field("_up_client_reserved1", &self._up_client_reserved1)
            .field("_up_client_reserved2", &self._up_client_reserved2)
            .field("_up_client_reserved3", &self._up_client_reserved3)
            .field("_up_client_reserved4", &self._up_client_reserved4)
            .field("_up_client_reserved5", &self._up_client_reserved5)
            .field("_up_client_reserved6", &self._up_client_reserved6)
            .field("_up_client_reserved7", &self._up_client_reserved7)
            .field("_up_client_reserved8", &self._up_client_reserved8)
            .finish()
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct _UpClientPrivate {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type UpClientPrivate = _UpClientPrivate;

#[derive(Copy, Clone)]
#[repr(C)]
pub struct UpDeviceClass {
    pub parent_class: gobject::GObjectClass,
    pub _up_device_reserved1: Option<unsafe extern "C" fn()>,
    pub _up_device_reserved2: Option<unsafe extern "C" fn()>,
    pub _up_device_reserved3: Option<unsafe extern "C" fn()>,
    pub _up_device_reserved4: Option<unsafe extern "C" fn()>,
    pub _up_device_reserved5: Option<unsafe extern "C" fn()>,
    pub _up_device_reserved6: Option<unsafe extern "C" fn()>,
    pub _up_device_reserved7: Option<unsafe extern "C" fn()>,
    pub _up_device_reserved8: Option<unsafe extern "C" fn()>,
}

impl ::std::fmt::Debug for UpDeviceClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("UpDeviceClass @ {self:p}"))
            .field("_up_device_reserved1", &self._up_device_reserved1)
            .field("_up_device_reserved2", &self._up_device_reserved2)
            .field("_up_device_reserved3", &self._up_device_reserved3)
            .field("_up_device_reserved4", &self._up_device_reserved4)
            .field("_up_device_reserved5", &self._up_device_reserved5)
            .field("_up_device_reserved6", &self._up_device_reserved6)
            .field("_up_device_reserved7", &self._up_device_reserved7)
            .field("_up_device_reserved8", &self._up_device_reserved8)
            .finish()
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct _UpDevicePrivate {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type UpDevicePrivate = _UpDevicePrivate;

#[derive(Copy, Clone)]
#[repr(C)]
pub struct UpHistoryItemClass {
    pub parent_class: gobject::GObjectClass,
}

impl ::std::fmt::Debug for UpHistoryItemClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("UpHistoryItemClass @ {self:p}"))
            .field("parent_class", &self.parent_class)
            .finish()
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct _UpHistoryItemPrivate {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type UpHistoryItemPrivate = _UpHistoryItemPrivate;

#[derive(Copy, Clone)]
#[repr(C)]
pub struct UpStatsItemClass {
    pub parent_class: gobject::GObjectClass,
}

impl ::std::fmt::Debug for UpStatsItemClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("UpStatsItemClass @ {self:p}"))
            .field("parent_class", &self.parent_class)
            .finish()
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct _UpStatsItemPrivate {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type UpStatsItemPrivate = _UpStatsItemPrivate;

// Classes
#[derive(Copy, Clone)]
#[repr(C)]
pub struct UpClient {
    pub parent: gobject::GObject,
    pub priv_: *mut UpClientPrivate,
}

impl ::std::fmt::Debug for UpClient {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("UpClient @ {self:p}"))
            .field("parent", &self.parent)
            .field("priv_", &self.priv_)
            .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct UpDevice {
    pub parent: gobject::GObject,
    pub priv_: *mut UpDevicePrivate,
}

impl ::std::fmt::Debug for UpDevice {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("UpDevice @ {self:p}"))
            .field("parent", &self.parent)
            .field("priv_", &self.priv_)
            .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct UpHistoryItem {
    pub parent: gobject::GObject,
    pub priv_: *mut UpHistoryItemPrivate,
}

impl ::std::fmt::Debug for UpHistoryItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("UpHistoryItem @ {self:p}"))
            .field("parent", &self.parent)
            .field("priv_", &self.priv_)
            .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct UpStatsItem {
    pub parent: gobject::GObject,
    pub priv_: *mut UpStatsItemPrivate,
}

impl ::std::fmt::Debug for UpStatsItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("UpStatsItem @ {self:p}"))
            .field("parent", &self.parent)
            .field("priv_", &self.priv_)
            .finish()
    }
}

unsafe extern "C" {

    //=========================================================================
    // UpClient
    //=========================================================================
    pub fn up_client_get_type() -> GType;
    pub fn up_client_new() -> *mut UpClient;
    pub fn up_client_new_finish(
        res: *mut gio::GAsyncResult,
        error: *mut *mut glib::GError,
    ) -> *mut UpClient;
    pub fn up_client_new_full(
        cancellable: *mut gio::GCancellable,
        error: *mut *mut glib::GError,
    ) -> *mut UpClient;
    pub fn up_client_new_async(
        cancellable: *mut gio::GCancellable,
        callback: gio::GAsyncReadyCallback,
        user_data: gpointer,
    );
    pub fn up_client_get_critical_action(client: *mut UpClient) -> *mut c_char;
    pub fn up_client_get_daemon_version(client: *mut UpClient) -> *const c_char;
    pub fn up_client_get_devices(client: *mut UpClient) -> *mut glib::GPtrArray;
    pub fn up_client_get_devices2(client: *mut UpClient) -> *mut glib::GPtrArray;
    pub fn up_client_get_devices_async(
        client: *mut UpClient,
        cancellable: *mut gio::GCancellable,
        callback: gio::GAsyncReadyCallback,
        user_data: gpointer,
    );
    pub fn up_client_get_devices_finish(
        client: *mut UpClient,
        res: *mut gio::GAsyncResult,
        error: *mut *mut glib::GError,
    ) -> *mut glib::GPtrArray;
    pub fn up_client_get_display_device(client: *mut UpClient) -> *mut UpDevice;
    pub fn up_client_get_lid_is_closed(client: *mut UpClient) -> gboolean;
    pub fn up_client_get_lid_is_present(client: *mut UpClient) -> gboolean;
    pub fn up_client_get_on_battery(client: *mut UpClient) -> gboolean;

    //=========================================================================
    // UpDevice
    //=========================================================================
    pub fn up_device_get_type() -> GType;
    pub fn up_device_new() -> *mut UpDevice;
    pub fn up_device_kind_from_string(type_: *const c_char) -> UpDeviceKind;
    pub fn up_device_kind_to_string(type_enum: UpDeviceKind) -> *const c_char;
    pub fn up_device_level_from_string(level: *const c_char) -> UpDeviceLevel;
    pub fn up_device_level_to_string(level_enum: UpDeviceLevel) -> *const c_char;
    pub fn up_device_state_from_string(state: *const c_char) -> UpDeviceState;
    pub fn up_device_state_to_string(state_enum: UpDeviceState) -> *const c_char;
    pub fn up_device_technology_from_string(technology: *const c_char) -> UpDeviceTechnology;
    pub fn up_device_technology_to_string(technology_enum: UpDeviceTechnology) -> *const c_char;
    pub fn up_device_get_history_sync(
        device: *mut UpDevice,
        type_: *const c_char,
        timespec: c_uint,
        resolution: c_uint,
        cancellable: *mut gio::GCancellable,
        error: *mut *mut glib::GError,
    ) -> *mut glib::GPtrArray;
    pub fn up_device_get_object_path(device: *mut UpDevice) -> *const c_char;
    pub fn up_device_get_statistics_sync(
        device: *mut UpDevice,
        type_: *const c_char,
        cancellable: *mut gio::GCancellable,
        error: *mut *mut glib::GError,
    ) -> *mut glib::GPtrArray;
    pub fn up_device_refresh_sync(
        device: *mut UpDevice,
        cancellable: *mut gio::GCancellable,
        error: *mut *mut glib::GError,
    ) -> gboolean;
    pub fn up_device_set_object_path_sync(
        device: *mut UpDevice,
        object_path: *const c_char,
        cancellable: *mut gio::GCancellable,
        error: *mut *mut glib::GError,
    ) -> gboolean;
    pub fn up_device_to_text(device: *mut UpDevice) -> *mut c_char;

    //=========================================================================
    // UpHistoryItem
    //=========================================================================
    pub fn up_history_item_get_type() -> GType;
    pub fn up_history_item_new() -> *mut UpHistoryItem;
    pub fn up_history_item_get_state(history_item: *mut UpHistoryItem) -> UpDeviceState;
    pub fn up_history_item_get_time(history_item: *mut UpHistoryItem) -> c_uint;
    pub fn up_history_item_get_value(history_item: *mut UpHistoryItem) -> c_double;
    pub fn up_history_item_set_from_string(
        history_item: *mut UpHistoryItem,
        text: *const c_char,
    ) -> gboolean;
    pub fn up_history_item_set_state(history_item: *mut UpHistoryItem, state: UpDeviceState);
    pub fn up_history_item_set_time(history_item: *mut UpHistoryItem, time: c_uint);
    pub fn up_history_item_set_time_to_present(history_item: *mut UpHistoryItem);
    pub fn up_history_item_set_value(history_item: *mut UpHistoryItem, value: c_double);
    pub fn up_history_item_to_string(history_item: *mut UpHistoryItem) -> *mut c_char;

    //=========================================================================
    // UpStatsItem
    //=========================================================================
    pub fn up_stats_item_get_type() -> GType;
    pub fn up_stats_item_new() -> *mut UpStatsItem;
    pub fn up_stats_item_get_accuracy(stats_item: *mut UpStatsItem) -> c_double;
    pub fn up_stats_item_get_value(stats_item: *mut UpStatsItem) -> c_double;
    pub fn up_stats_item_set_accuracy(stats_item: *mut UpStatsItem, accuracy: c_double);
    pub fn up_stats_item_set_value(stats_item: *mut UpStatsItem, value: c_double);

}
