// This file was generated by gir (https://github.com/gtk-rs/gir)
// from upower-gir-files
// DO NOT EDIT

#![cfg(unix)]

use std::env;
use std::error::Error;
use std::ffi::OsString;
use std::mem::{align_of, size_of};
use std::path::Path;
use std::process::{Command, Stdio};
use std::str;
use tempfile::Builder;
use upower_glib_sys::*;

static PACKAGES: &[&str] = &["upower-glib"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Self, Box<dyn Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        // For _Generic
        args.push("-std=c11".to_owned());
        // For %z support in printf when using MinGW.
        args.push("-D__USE_MINGW_ANSI_STDIO".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Self { args })
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {cmd:?} failed, {status}").into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<dyn Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{name} {err}").into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<dyn Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let pkg_config = env::var_os("PKG_CONFIG").unwrap_or_else(|| OsString::from("pkg-config"));
    let mut cmd = Command::new(pkg_config);
    cmd.arg("--cflags");
    cmd.args(packages);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn summary(&self) -> String {
        format!("{} passed; {} failed", self.passed, self.failed)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let mut c_constants: Vec<(String, String)> = Vec::new();

    for l in get_c_output("constant").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing ';' separator");
        c_constants.push((name.to_owned(), value.to_owned()));
    }

    let mut results = Results::default();

    for ((rust_name, rust_value), (c_name, c_value)) in
        RUST_CONSTANTS.iter().zip(c_constants.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_value != c_value {
            results.record_failed();
            eprintln!(
                "Constant value mismatch for {rust_name}\nRust: {rust_value:?}\nC:    {c_value:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let mut c_layouts = Vec::new();

    for l in get_c_output("layout").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing first ';' separator");
        let (size, alignment) = value.split_once(';').expect("Missing second ';' separator");
        let size = size.parse().expect("Failed to parse size");
        let alignment = alignment.parse().expect("Failed to parse alignment");
        c_layouts.push((name.to_owned(), Layout { size, alignment }));
    }

    let mut results = Results::default();

    for ((rust_name, rust_layout), (c_name, c_layout)) in RUST_LAYOUTS.iter().zip(c_layouts.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_layout != c_layout {
            results.record_failed();
            eprintln!("Layout mismatch for {rust_name}\nRust: {rust_layout:?}\nC:    {c_layout:?}",);
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

fn get_c_output(name: &str) -> Result<String, Box<dyn Error>> {
    let tmpdir = Builder::new().prefix("abi").tempdir()?;
    let exe = tmpdir.path().join(name);
    let c_file = Path::new("tests").join(name).with_extension("c");

    let cc = Compiler::new().expect("configured compiler");
    cc.compile(&c_file, &exe)?;

    let mut cmd = Command::new(exe);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }

    Ok(String::from_utf8(out.stdout)?)
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    (
        "UpClient",
        Layout {
            size: size_of::<UpClient>(),
            alignment: align_of::<UpClient>(),
        },
    ),
    (
        "UpClientClass",
        Layout {
            size: size_of::<UpClientClass>(),
            alignment: align_of::<UpClientClass>(),
        },
    ),
    (
        "UpDevice",
        Layout {
            size: size_of::<UpDevice>(),
            alignment: align_of::<UpDevice>(),
        },
    ),
    (
        "UpDeviceClass",
        Layout {
            size: size_of::<UpDeviceClass>(),
            alignment: align_of::<UpDeviceClass>(),
        },
    ),
    (
        "UpDeviceKind",
        Layout {
            size: size_of::<UpDeviceKind>(),
            alignment: align_of::<UpDeviceKind>(),
        },
    ),
    (
        "UpDeviceLevel",
        Layout {
            size: size_of::<UpDeviceLevel>(),
            alignment: align_of::<UpDeviceLevel>(),
        },
    ),
    (
        "UpDeviceState",
        Layout {
            size: size_of::<UpDeviceState>(),
            alignment: align_of::<UpDeviceState>(),
        },
    ),
    (
        "UpDeviceTechnology",
        Layout {
            size: size_of::<UpDeviceTechnology>(),
            alignment: align_of::<UpDeviceTechnology>(),
        },
    ),
    (
        "UpHistoryItem",
        Layout {
            size: size_of::<UpHistoryItem>(),
            alignment: align_of::<UpHistoryItem>(),
        },
    ),
    (
        "UpHistoryItemClass",
        Layout {
            size: size_of::<UpHistoryItemClass>(),
            alignment: align_of::<UpHistoryItemClass>(),
        },
    ),
    (
        "UpStatsItem",
        Layout {
            size: size_of::<UpStatsItem>(),
            alignment: align_of::<UpStatsItem>(),
        },
    ),
    (
        "UpStatsItemClass",
        Layout {
            size: size_of::<UpStatsItemClass>(),
            alignment: align_of::<UpStatsItemClass>(),
        },
    ),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("(gint) UP_DEVICE_KIND_BATTERY", "2"),
    ("(gint) UP_DEVICE_KIND_BLUETOOTH_GENERIC", "28"),
    ("(gint) UP_DEVICE_KIND_CAMERA", "25"),
    ("(gint) UP_DEVICE_KIND_COMPUTER", "11"),
    ("(gint) UP_DEVICE_KIND_GAMING_INPUT", "12"),
    ("(gint) UP_DEVICE_KIND_HEADPHONES", "19"),
    ("(gint) UP_DEVICE_KIND_HEADSET", "17"),
    ("(gint) UP_DEVICE_KIND_KEYBOARD", "6"),
    ("(gint) UP_DEVICE_KIND_LAST", "29"),
    ("(gint) UP_DEVICE_KIND_LINE_POWER", "1"),
    ("(gint) UP_DEVICE_KIND_MEDIA_PLAYER", "9"),
    ("(gint) UP_DEVICE_KIND_MODEM", "15"),
    ("(gint) UP_DEVICE_KIND_MONITOR", "4"),
    ("(gint) UP_DEVICE_KIND_MOUSE", "5"),
    ("(gint) UP_DEVICE_KIND_NETWORK", "16"),
    ("(gint) UP_DEVICE_KIND_OTHER_AUDIO", "21"),
    ("(gint) UP_DEVICE_KIND_PDA", "7"),
    ("(gint) UP_DEVICE_KIND_PEN", "13"),
    ("(gint) UP_DEVICE_KIND_PHONE", "8"),
    ("(gint) UP_DEVICE_KIND_PRINTER", "23"),
    ("(gint) UP_DEVICE_KIND_REMOTE_CONTROL", "22"),
    ("(gint) UP_DEVICE_KIND_SCANNER", "24"),
    ("(gint) UP_DEVICE_KIND_SPEAKERS", "18"),
    ("(gint) UP_DEVICE_KIND_TABLET", "10"),
    ("(gint) UP_DEVICE_KIND_TOUCHPAD", "14"),
    ("(gint) UP_DEVICE_KIND_TOY", "27"),
    ("(gint) UP_DEVICE_KIND_UNKNOWN", "0"),
    ("(gint) UP_DEVICE_KIND_UPS", "3"),
    ("(gint) UP_DEVICE_KIND_VIDEO", "20"),
    ("(gint) UP_DEVICE_KIND_WEARABLE", "26"),
    ("(gint) UP_DEVICE_LEVEL_ACTION", "5"),
    ("(gint) UP_DEVICE_LEVEL_CRITICAL", "4"),
    ("(gint) UP_DEVICE_LEVEL_DISCHARGING", "2"),
    ("(gint) UP_DEVICE_LEVEL_FULL", "8"),
    ("(gint) UP_DEVICE_LEVEL_HIGH", "7"),
    ("(gint) UP_DEVICE_LEVEL_LAST", "9"),
    ("(gint) UP_DEVICE_LEVEL_LOW", "3"),
    ("(gint) UP_DEVICE_LEVEL_NONE", "1"),
    ("(gint) UP_DEVICE_LEVEL_NORMAL", "6"),
    ("(gint) UP_DEVICE_LEVEL_UNKNOWN", "0"),
    ("(gint) UP_DEVICE_STATE_CHARGING", "1"),
    ("(gint) UP_DEVICE_STATE_DISCHARGING", "2"),
    ("(gint) UP_DEVICE_STATE_EMPTY", "3"),
    ("(gint) UP_DEVICE_STATE_FULLY_CHARGED", "4"),
    ("(gint) UP_DEVICE_STATE_LAST", "7"),
    ("(gint) UP_DEVICE_STATE_PENDING_CHARGE", "5"),
    ("(gint) UP_DEVICE_STATE_PENDING_DISCHARGE", "6"),
    ("(gint) UP_DEVICE_STATE_UNKNOWN", "0"),
    ("(gint) UP_DEVICE_TECHNOLOGY_LAST", "7"),
    ("(gint) UP_DEVICE_TECHNOLOGY_LEAD_ACID", "4"),
    ("(gint) UP_DEVICE_TECHNOLOGY_LITHIUM_ION", "1"),
    ("(gint) UP_DEVICE_TECHNOLOGY_LITHIUM_IRON_PHOSPHATE", "3"),
    ("(gint) UP_DEVICE_TECHNOLOGY_LITHIUM_POLYMER", "2"),
    ("(gint) UP_DEVICE_TECHNOLOGY_NICKEL_CADMIUM", "5"),
    ("(gint) UP_DEVICE_TECHNOLOGY_NICKEL_METAL_HYDRIDE", "6"),
    ("(gint) UP_DEVICE_TECHNOLOGY_UNKNOWN", "0"),
    ("UP_MAJOR_VERSION", "1"),
    ("UP_MICRO_VERSION", "0"),
    ("UP_MINOR_VERSION", "91"),
];
