// This file was generated by gir (https://github.com/gtk-rs/gir)
// from upower-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "UpClient", sizeof(UpClient), alignof(UpClient));
    printf("%s;%zu;%zu\n", "UpClientClass", sizeof(UpClientClass), alignof(UpClientClass));
    printf("%s;%zu;%zu\n", "UpDevice", sizeof(UpDevice), alignof(UpDevice));
    printf("%s;%zu;%zu\n", "UpDeviceClass", sizeof(UpDeviceClass), alignof(UpDeviceClass));
    printf("%s;%zu;%zu\n", "UpDeviceKind", sizeof(UpDeviceKind), alignof(UpDeviceKind));
    printf("%s;%zu;%zu\n", "UpDeviceLevel", sizeof(UpDeviceLevel), alignof(UpDeviceLevel));
    printf("%s;%zu;%zu\n", "UpDeviceState", sizeof(UpDeviceState), alignof(UpDeviceState));
    printf("%s;%zu;%zu\n", "UpDeviceTechnology", sizeof(UpDeviceTechnology), alignof(UpDeviceTechnology));
    printf("%s;%zu;%zu\n", "UpHistoryItem", sizeof(UpHistoryItem), alignof(UpHistoryItem));
    printf("%s;%zu;%zu\n", "UpHistoryItemClass", sizeof(UpHistoryItemClass), alignof(UpHistoryItemClass));
    printf("%s;%zu;%zu\n", "UpStatsItem", sizeof(UpStatsItem), alignof(UpStatsItem));
    printf("%s;%zu;%zu\n", "UpStatsItemClass", sizeof(UpStatsItemClass), alignof(UpStatsItemClass));
    return 0;
}
